#!/bin/bash 
#file: advfulldiffsteps

subj=$1
WORKDIR=$2
#FS_DIR=$3

#Full diffusion pipeline, from pre-processing to connectome construction - using the advanced version

#Advanced preprocessing
#Parameters: mosaic fullrevsequence multiband (1 if yes)

advpreproc $subj $WORKDIR 1 0 1
 
#Segmentation, parcellation and co-registration of T1 images

segparcandcoregT1 $subj $WORKDIR DST

#Fiber construction and connectome construction

advfibertrackandcntmecon $subj $WORKDIR 1 50M DST


