#!/bin/bash 
#file: advfulldiffsteps

subj=$1
WORKDIR=$2
#FS_DIR=$3

#arguments to be set
ismultiband=1
parc=DST
ismultishell=1
numfibers=25M


#Full diffusion pipeline, from pre-processing to connectome construction - using the advanced version

#Advanced preprocessing
#Parameters: mosaic fullrevsequence multiband (1 if yes)

#advpreproc $subj $WORKDIR $ismultiband
 
#Segmentation, parcellation and co-registration of T1 images

segparcandcoregT1 $subj $WORKDIR $parc

#Fiber construction and connectome construction

#advfibertrackandcntmecon $subj $WORKDIR $ismultishell $numfibers $parc


