#!/bin/bash 

subj=$1
WORKDIR=$2

#Full diffusion pipeline, from pre-processing to connectome construction

#Basic preprocessing

basicpreproc $subj $WORKDIR

#Fiber construction

basicfibertrack $subj $WORKDIR 5M

#Connectome construction

basiccntmecon $subj $WORKDIR /mnt/backedup/home/alistaiP/base/parc2fmrib.nii 5M 512
