#!/bin/bash

#SBATCH -n 1 # 1 per CPU
#SBATCH -c 8 # number of cpus per task
#SBATCH --nice=10
#SBATCH -p blade-a

source /daten/bin/setup_fsl-5.0.9-cscor.sh
source /beegfs/bin/setup_freesurfer-6.0.0.sh

MRTRIX=/beegfs/scratch/tnc_scratch/aperry/MRtrix/RC3
export PATH=${MRTRIX}/bin:$PATH

export OMP_NUM_THREADS=8

#setup configuration file
echo "TmpFileDir: /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/tmp" > /home/aperry/.mrtrix.conf 
echo "ScriptTmpDir: /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/scripttmp" >> /home/aperry/.mrtrix.conf

####
#Find all scripting files
#currdir=$(pwd)
pipedir=&&&&
PATH=$PATH$( find $pipedir/ -not -path '*/\.*'  -type d -printf ":%p" )
#export PATH:$PATH

#Extract ID of subject and their corresponding folder holding raw image files

subj=@@@@
subjDIRECTORY=????

cd $subjDIRECTORY

%%%% #"%%%%" will match to the string  that corresponds to your personalised batch script, or preferred pipeline
 
