#!/bin/bash
#Template file which sets up SGE requirements for all jobs

export OMP_NUM_THREADS=8

####
#Find all scripting files
#currdir=$(pwd)
pipedir=&&&&
PATH=$PATH$( find $pipedir/ -not -path '*/\.*'  -type d -printf ":%p" )
#export PATH:$PATH

####
#Load all required software
MRTRIXDIR=/clusterdata/apps/mrtrix3/bin

FSLDIR=/clusterdata/apps/fsl
. ${FSLDIR}/etc/fslconf/fsl.sh

export FREESURFER_HOME=/clusterdata/apps/freesurfer-6.0
source $FREESURFER_HOME/SetUpFreeSurfer.sh

ANTsDIR=/clusterdata/apps/ANTs/bin

export PATH=$PATH=${MRTRIXDIR}:${FSLDIR}:${ANTsDIR}:$PATH

#Extract ID of subject and their corresponding folder holding raw image files

subj=@@@@
subjDIRECTORY=????

cd $subjDIRECTORY

%%%% #"%%%%" will match to the string  that corresponds to your personalised batch script, or preferred pipeline
 
