#!/bin/bash 
#file: streamlines
# This file will compute the connectome exemplars given a parcellation image, connectome node assignments
# and the track file given by the pipeline. Run this if you would like to visualise streamlines for your
# subject.

subj=$1
WORKDIR=$2

cd $WORKDIR/Diff/$subj/preproc

# Run connectome2tck function
# -files single to specify the single output file of the streamlines in "exem.tck"
# -exemplars constrains the streamlines to the nodes from parcellation image "parc.nii"

connectome2tck -exemplars parc.nii -files single 25M.tck streamlineassignment.txt exem.tck -nthreads $ncpus -force
