#!/bin/bash
#usage: electrode_roi subj WORKDIR PARCDIR COORDS_FILE

subj=$1
WORKDIR=$2
PARCDIR=$3
COORDS_FILE=$4

mkdir -p $WORKDIR/$PARCDIR/coords/$subj
COORD_DIR=$WORKDIR/$PARCDIR/coords/$subj
## setup proper file structure
COORDS_FILE=$WORKDIR/$COORDS_FILE

if [ "$rundir" != "$WORKDIR/$PARCDIR/coords/$subj" ]; then
cd $WORKDIR/$PARCDIR/coords/$subj
fi

#get coords from csv

IFS=','
while read -r X Y Z
do

  echo "Constructing ROI for MNI coords $X $Y $Z"
  fslmaths $WORKDIR/$PARCDIR/mni_icbm152_t1_tal_nlin_asym_09c_brain.nii -mul 0 -add 1 -roi $X 1 $Y 1 $Z 1 $COORD_DIR/$X$Y$Z_point -odt float
  fslmaths $COORD_DIR/$X$Y$Z_point -kernel sphere 2 -fmean $COORD_DIR/$X$Y$Z_sphere
  fslmaths $COORD_DIR/$X$Y$Z_sphere -bin $COORD_DIR/$X$Y$Z_electrode_MNI
  rm $COORD_DIR/$X$Y$Z_point
  rm $COORD_DIR/$X$Y$Z_sphere
  gunzip $COORD_DIR/$X$Y$Z_electrode_MNI.nii.gz
  
done < $COORDS_FILE
