#!/bin/bash

# File used for collecting AFD values from pairwise electrode-to-electrode 
# tracts in individual patients and making a matrix of them

subj=$1
WORKDIR=$2
NORMDIR=$3

#setup proper directory structure
TRACKDIR=${WORKDIR}/${NORMDIR}/electrodetracking/${subj}
cd $TRACKDIR

echo "0x0" > ${subj}_cntme.txt

#construct matrix
declare -A matrix

shopt -s nullglob
l="$(wc -l < ${WORKDIR}/${subj}_seeds.txt)"
for ((i=1;i<=l;i++)) do
  for ((j=1;j<=l;j++)) do
    seed="$(awk "NR == ${i}" ${WORKDIR}/${subj}_seeds.txt)"
    target="$(awk "NR == ${j}" ${WORKDIR}/${subj}_seeds.txt)"
    file="$(find ./* \( -name "${seed}*" -a -name "*to_${target}*" -a -name "*COMB_AFD.txt" \) )"
  
    if [[ -f $file ]]
    then
      if [[ -s $file ]]
      then
        matrix[$j]="$(find ./* \( -name "${seed}*" -a -name "*to_${target}*" -a -name "*COMB_AFD.txt" \) -exec cat {} \; )"
      else
        matrix[$j]=0
      fi
    else
      matrix[$j]=0
    fi
  done
  echo "${matrix[@]}" > {i}.txt
  paste ${subj}_cntme.txt {i}.txt | column -s $'\t' -t
done
