#!/bin/bash
#usage: electrode_roi subj WORKDIR PARCDIR COORDS_FILE

subj=$1
WORKDIR=$2
PARCDIR=$3
COORDS_FILE=$4

mkdir -p $WORKDIR/$PARCDIR/coords/$subj
COORD_DIR=$WORKDIR/$PARCDIR/coords/$subj
## setup proper file structure
COORDS_FILE=$WORKDIR/$COORDS_FILE

if [ "$rundir" != $COORD_DIR ]; then
cd $COORD_DIR
fi

#get coords from csv


while IFS=',' read -r X Y Z
do

  echo "Constructing ROI for MNI coords $X $Y $Z"
  fslmaths $WORKDIR/$PARCDIR/mni_icbm152_t1_tal_nlin_asym_09c_brain.nii -mul 0 -add 1 -roi $X 1 $Y 1 $Z 1 0 1 ${X}_${Y}_${Z}_point -odt float
  fslmaths ${X}_${Y}_${Z}_point -kernel sphere 2 -fmean ${X}_${Y}_${Z}_sphere
  fslmaths ${X}_${Y}_${Z}_sphere -bin ${X}_${Y}_${Z}_electrode_MNI
  rm ${X}_${Y}_${Z}_point.nii.gz
  rm ${X}_${Y}_${Z}_sphere.nii.gz
  gunzip ${X}_${Y}_${Z}_electrode_MNI.nii.gz
  
done < $COORDS_FILE

#get rid of question marks

find . -type f -name '*\?*' | while read f; do mv "$f" "${f//\?/}"; done
