#!/bin/bash
#usage: seedbasedtracking $subj $WORKDIR $NORMDIR $PARCDIR $parcimageref $seedtracklist.txt

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2
NORMDIR=$3
PARCDIR=$4
parcimageref=$5
seedtracklist=$6

#convert to appropriate directory structure

DATADIR=${WORKDIR}/Diff
PARCDIR=${WORKDIR}/${PARCDIR}
seedtracklist=${WORKDIR}/${seedtracklist}

cd ${WORKDIR}/${NORMDIR}

mkdir -p ${WORKDIR}/${NORMDIR}/electrodetracking/${subj}
cd ${WORKDIR}/${NORMDIR}/electrodetracking/${subj}


#Setup transforms between FS, MNI, and Diff space

rsync ${DATADIR}/${subj}/preproc/brainFS.nii .

bet2 brainFS.nii brainFSbet -f 0.2 -m

gunzip brainFSbet.nii.gz

#add nthreads for ANTs

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$ncpus
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS

parcimageref=${parcimageref}.nii

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [brainFSintemp,brainFSintempWarped.nii.gz,brainFSintempInverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [${PARCDIR}/${parcimageref},brainFSbet.nii,1] --transform Rigid[0.1] --metric MI[${PARCDIR}/${parcimageref},brainFSbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[${PARCDIR}/${parcimageref},brainFSbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[${PARCDIR}/${parcimageref},brainFSbet.nii,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

#flirt -ref ${PARCDIR}/${parcimageref} -in brainFSbet.nii -omat FS2MNI.mat -out FS2MNI -dof 12

#convert_xfm -omat tempinbrainFS.mat -inverse FS2MNI.mat

c3d_affine_tool -ref brainFSintempWarped.nii.gz -src brainFSbet.nii -itk brainFSintemp0GenericAffine.mat -ras2fsl -o brainFSintemp-fsl.mat

#now inverse it

rsync ${DATADIR}/${subj}/preproc/FS2diff.mat .
rsync ${DATADIR}/${subj}/preproc/diff2FS.mat .

convert_xfm -omat tempinbrainFS.mat -inverse brainFSintemp-fsl.mat

convert_xfm -omat FS2diff.mat -inverse diff2FS.mat

#Setup seeds from seedtracklist

while read line

do 
seed=$(echo $line | cut -d " " -f 1) 
target=$(echo $line | cut -d " " -f 2)

echo "tracking for $seed to $target" #may do reverse later

#Setup STN seeds in diffusion space

if [[ -e ${seed}_diff.nii ]]; then

	if [[ -e ${target}_diff.nii ]]; then
		
		tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -seed_image ${seed}_diff.nii -include ${target}_diff.nii -mask ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${seed}_seeds.txt

		tckmap ${seed}_to_${target}.tck ${seed}_to_${target}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

		mrthreshold ${seed}_to_${target}_tdi.nii ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers

		#FA

		mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanFA.txt

		#MD

		mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanMD.txt

		#AFD

		afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -nthreads $ncpus -all_fixels -force -afd_map ${seed}_to_${target}_AFD.nii > ${seed}_to_${target}_AFD.txt

		#now reverse!

		tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -seed_image ${target}_diff.nii -include ${seed}_diff.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${target}_seeds.txt

		tckmap ${target}_to_${seed}.tck ${target}_to_${seed}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

		mrthreshold ${target}_to_${seed}_tdi.nii ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers

		#stats

		#FA

		mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanFA.txt
		#MD

		mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanMD.txt

		#AFD

		afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -nthreads $ncpus -all_fixels -force -afd_map ${target}_to_${seed}_AFD.nii > ${target}_to_${seed}_AFD.txt
	else
	
		flirt -in ${PARCDIR}/${target}.nii -ref brainFS.nii -applyxfm -init tempinbrainFS.mat -interp nearestneighbour -out ${target}_FS.nii.gz

		gunzip ${target}_FS.nii.gz -f

		mrconvert ${target}_FS.nii ${target}_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus

		flirt -in ${target}_FS_str.nii -ref ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -out ${target}_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

		gunzip ${target}_diff.nii.gz -f
		
		tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -seed_image ${seed}_diff.nii -include ${target}_diff.nii -mask ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${seed}_seeds.txt

                tckmap ${seed}_to_${target}.tck ${seed}_to_${target}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

		mrthreshold ${seed}_to_${target}_tdi.nii ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers

                #FA

                mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanFA.txt

                #MD

                mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanMD.txt

                #AFD

                afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -nthreads $ncpus -all_fixels -force -afd_map ${seed}_to_${target}_AFD.nii > ${seed}_to_${target}_AFD.txt

                #now reverse!

                tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -seed_image ${target}_diff.nii -include ${seed}_diff.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${target}_seeds.txt

                tckmap ${target}_to_${seed}.tck ${target}_to_${seed}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

                mrthreshold ${target}_to_${seed}_tdi.nii ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers

                #stats

                #FA

                mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanFA.txt
                #MD

                mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanMD.txt

                #AFD

                afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -nthreads $ncpus -all_fixels -force -afd_map ${target}_to_${seed}_AFD.nii > ${target}_to_${seed}_AFD.txt

	fi
else

	flirt -in ${PARCDIR}/${seed}.nii -ref brainFS.nii -applyxfm -init tempinbrainFS.mat -interp nearestneighbour -out ${seed}_FS.nii.gz

	gunzip ${seed}_FS.nii.gz -f

	mrconvert ${seed}_FS.nii ${seed}_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus

	flirt -in ${seed}_FS_str.nii -ref ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -out ${seed}_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

	gunzip ${seed}_diff.nii.gz -f

	tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -seed_image ${seed}_diff.nii -include ${target}_diff.nii -mask ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${seed}_seeds.txt

        tckmap ${seed}_to_${target}.tck ${seed}_to_${target}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

        mrthreshold ${seed}_to_${target}_tdi.nii ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers

        #FA

        mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanFA.txt

	#MD
        mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanMD.txt

        #AFD

        afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -nthreads $ncpus -all_fixels -force -afd_map ${seed}_to_${target}_AFD.nii > ${seed}_to_${target}_AFD.txt

        #now reverse!

        tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -seed_image ${target}_diff.nii -include ${seed}_diff.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${target}_seeds.txt

        tckmap ${target}_to_${seed}.tck ${target}_to_${seed}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

        mrthreshold ${target}_to_${seed}_tdi.nii ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers
        #stats

        #FA

        mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanFA.txt
        #MD

        mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${target}_to_${seed}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${target}_to_${seed}_meanMD.txt

        #AFD

        afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${target}_to_${seed}.tck -nthreads $ncpus -all_fixels -force -afd_map ${target}_to_${seed}_AFD.nii > ${target}_to_${seed}_AFD.txt


fi

done < $seedtracklist
