#!/bin/bash
#usage: electrode_roi subj WORKDIR PARCDIR COORDS_FILE

subj=$1
WORKDIR=$2
PARCDIR=$3
COORDS_FILE=$4

mkdir -p $WORKDIR/$PARCDIR/coords/$subj
COORD_DIR=$WORKDIR/$PARCDIR/coords/$subj
## setup proper file structure
COORDS_FILE=$WORKDIR/$COORDS_FILE
rm ${WORKDIR}/${subj}_seeds.txt
rm ${WORKDIR}/${subj}_tracklist.txt

if [ "$rundir" != $COORD_DIR ]; then
cd $COORD_DIR
fi

#get coords from csv

#delete carriage returns

sed -i 's/\r//g' $COORDS_FILE

while IFS=',' read -r X Y Z region
do

  echo "Constructing ROI for MNI coords $X $Y $Z in region $region"
  #convert to voxel coords
  v_x=$(($X*-1+90))
  v_y=$(($Y+126))
  v_z=$(($Z+72))
  echo "Equivalent to voxel coords $v_x $v_y $v_z"
  fslmaths ${FSLDIR}/data/standard/MNI152_T1_1mm_brain -mul 0 -add 1 -roi $v_x 1 $v_y 1 $v_z 1 0 1 ${v_x}_${v_y}_${v_z}_point -odt float
  fslmaths ${v_x}_${v_y}_${v_z}_point -kernel sphere 3 -fmean ${v_x}_${v_y}_${v_z}_sphere
  fslmaths ${v_x}_${v_y}_${v_z}_sphere -bin ${v_x}_${v_y}_${v_z}_electrode_MNI
  rm ${v_x}_${v_y}_${v_z}_point.nii.gz
  rm ${v_x}_${v_y}_${v_z}_sphere.nii.gz
  gunzip -f ${v_x}_${v_y}_${v_z}_electrode_MNI.nii.gz
  
done < $COORDS_FILE

#setup blank image so that fsl can put rois onto it

fslmaths ${FSLDIR}/data/standard/MNI152_T1_1mm_brain -uthr 0 -thr 0 blank

for file in *.nii
do

  echo "Queuing ${file} to parcellation image..."
  #convert to single list of files to add to parcellation
  var=$var' -add '$file
  
done

#make parcellation image from electrode rois
fslmaths blank.nii.gz $var ${subj}_parc
gunzip -f ${subj}_parc.nii.gz

#cleanup
rm blank.nii.gz
