#!/bin/bash

# File used for collecting AFD values from pairwise electrode-to-electrode 
# tracts in individual patients and making a matrix of them

WORKDIR=$1
NORMDIR=$2
#setup proper directory structure
TRACKDIR=${WORKDIR}/${NORMDIR}/electrodetracking/${subj}
cd $TRACKDIR

#construct matrix
declare -A matrix

shopt -s nullglob
l="$(wc -l < ${subj}_seeds.txt)"
for ((i=1;i<=l;i++)) do
  for ((j=1;j<=l;j++)) do
  seed="$(awk "NR == ${i}" ${subj}_seeds.txt)"
  target="$(awk "NR == ${j}" ${subj}_seeds.txt)"
  matrix[$i,$j]="$(find ./* \( -name "${seed}*" -a -name "*${target}*" -a -name "*COMB*" \) -exec cat {} \; )"
  done
done

echo "${matrix[@]}" > ${WORKDIR}/${NORMDIR}/${subj}_cntme.txt
