#!/bin/bash
#usage: mniseg subj WORKDIR

subj=$1
WORKDIR=$2

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

#ROIs
#insula
fslmaths T1bet.nii.gz -mul 0 -add 1 -roi 50 1 118 1 106 1 0 1 insula_point.nii.gz -odt float
fslmaths insula_point.nii.gz -kernel sphere 10 -fmean insula_sphere.nii.gz -odt float
fslmaths insula_sphere.nii.gz -bin insula_mask.nii.gz

#temporal pole
fslmaths T1bet.nii.gz -mul 0 -add 1 -roi 127 1 114 1 67 1 0 1 temp_pole_point.nii.gz -odt float
fslmaths temp_pole_point.nii.gz -kernel sphere 10 -fmean temp_pole_sphere.nii.gz -odt float
fslmaths temp_pole_sphere.nii.gz -bin temp_pole_mask.nii.gz
