#!/bin/bash
#usage: mniseg subj WORKDIR

subj=$1
WORKDIR=$2

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

#ROIs
#Broca's area
fslmaths BA44 -add BA45 -thr 50 -bin Broca

#temporal pole
fslmaths BA38 -thr 50 -bin TempPole

#ACC
fslmaths BA24 -add BA32 -add BA33 -thr 50 -bin ACC
