#!/bin/bash
#file : prepareglasserparc

#SBATCH -c 5 # number of cpus per task
#SBATCH --nice=10
#SBATCH -p blade-a

source /daten/bin/setup_fsl-5.0.9-cscor.sh
source /beegfs/v1/bin2/setup_freesurfer_530.sh

MRTRIX=/beegfs/scratch/tnc_scratch/aperry/MRtrix/02032017
export PATH=${MRTRIX}/release/bin:${MRTRIX}/scripts:$PATH

WORKDIR=/beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome
OUTDIR=HCPMMP1out

export OMP_NUM_THREADS=8

export SUBJECTS_DIR=${WORKDIR}/FS

cd $SUBJECTS_DIR

find ${WORKDIR}/Raw/* -maxdepth 0 -type d | awk -F "/" '{print $NF}' - > subjlist.txt

#printf $(basename $subjfilelist) > subjlist.txt

if [ ! -d fsaverage ]; then

rsync -vaz ${FREESURFER_HOME}/subjects/fsaverage .

fi

if [ ! -f create_subj_volume_parcellation.sh ]; then

rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/miscscripts/create_subj_volume_parcellation.sh .

fi

if [ ! -f lh.HCPMMP1.annot ]; then

rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/data/lh.HCPMMP1.annot .
rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/data/rh.HCPMMP1.annot .

fi

bash create_subj_volume_parcellation.sh -L subjlist.txt -a HCPMMP1 -d ${OUTDIR} -m "YES"
