#!/bin/bash
#file : prepareglasserparc
#usage: prepareglasserparc <subj> <WORKDIR> <OUTDIR>

subj=$1
WORKDIR=$2
OUTDIR=$3

export SUBJECTS_DIR=${WORKDIR}/FS

cd $SUBJECTS_DIR

if [ ! -d fsaverage ]; then

rsync -vaz ${FREESURFER_HOME}/subjects/fsaverage .

fi

if [ ! -f create_subj_volume_parcellation.sh ]; then

rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/miscscripts/create_subj_volume_parcellation.sh .

fi

if [ ! -f lh.HCPMMP1.annot ]; then

rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/data/lh.HCPMMP1.annot .
rsync /beegfs/scratch/tnc_scratch/kfo_pd_connectome/PD_connectome/diffusion-pipeline/data/rh.HCPMMP1.annot .

fi

printf ${subj} > ${subj}.txt

bash create_subj_volume_parcellation.sh -L ${subj}.txt -a HCPMMP1 -d ${OUTDIR} -m "YES"
