#!/bin/bash
#file : prepareglasserparc
#usage: prepareglasserparc <subj> <WORKDIR> <OUTDIR>

subj=$1
WORKDIR=$2

SUBJECTS_DIR=${WORKDIR}/FS

cd $SUBJECTS_DIR

if [ ! -d fsaverage ]; then

rsync -vaz ${FREESURFER_HOME}/subjects/average .

fi

if [ ! -f create_subj_volume_parcellation.sh ]; then

rsync /mnt/backedup/home/alistaiP/bundle/test/diffusion-pipeline/miscscripts/create_subj_volume_parcellation.sh .

fi

if [ ! -f lh.HCPMMP1.annot ]; then

rsync /mnt/backedup/home/alistaiP/bundle/test/diffusion-pipeline/lh.HCPMMP1.annot .
rsync /mnt/backedup/home/alistaiP/bundle/test/diffusion-pipeline/rh.HCPMMP1.annot .

fi

printf ${subj} > ${subj}.txt

bash create_subj_volume_parcellation -L ${subj}.txt -a HCPMMP1 -d ${OUTDIR}






