#!/bin/bash
#usage: tracks4cfe WORKDIR NORMDIR

#compulsory arguments that are called automatically:
#subj=$1

WORKDIR=$1
NORMDIR=$2

TEMPLATEDIR=fodtemplate

cd ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}

tckgen -maxlen 250 -minlen 10 -power 1.0 fod_template.mif -seed_image voxel_mask.mif -mask voxel_mask.mif -select 100M 100M_defang.tck -nthreads 10 --force

tcksift 100M_defang.tck fod_template.mif 10M_defang_sift.tck -term_number 10000000 -nthreads 10 --force
