#!/bin/bash
#usage: tracks4cfe WORKDIR NORMDIR TEMPLATEDIR

#compulsory arguments that are called automatically:
#subj=$1

WORKDIR=$1
NORMDIR=$2
COGVARS=$3

TEMPLATEDIR=fodtemplate

cd ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}/fixels 

#find ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}/fixels/fdc/*Patient* -name "*Patient*" -maxdepth 0 > fdcfiles.txt
#awk -F "/" '{print $NF}' fdcfiles.txt > subjs.txt

fixelcfestats fd filelist.txt ${COGVARS}.txt contrast_matrix_betgrps.txt ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}/tracks_2_million_defang_sift.tck stats_fd_$COGVARS -nperms 100 -force -nthreads 10 -neg 

fixelcfestats log_fc filelist.txt ${COGVARS}.txt contrast_matrix_betgrps.txt ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}/tracks_2_million_defang_sift.tck stats_logfc_$COGVARS -neg -nperms 100 -force -nthreads 10 

fixelcfestats fdc filelist.txt ${COGVARS}.txt contrast_matrix_betgrps.txt ${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}/tracks_2_million_defang_sift.tck stats_fdc_$COGVARS -nperms 100 -force -nthreads 10 -neg
