#!/bin/bash
#file: fodmodulationandfdcalc
#usage: fodmodulationandfdcalc $WORKDIR $OUTDIR

WORKDIR=$1
NORMDIR=$2

TEMPLATEDIR=fodtemplate

cd ${WORKDIR}/${NORMDIR}

DATADIR=${WORKDIR}/${NORMDIR}/${TEMPLATEDIR}

foreach -10 ${WORKDIR}/${NORMDIR}/upsample/FODS/wm/*.mif : srun -c 1 mrtransform IN -warp ${DATADIR}/warps/UNIP2template_warp.mif -noreorientation ${DATADIR}/warps/UNIPwm_in_template_space.mif -nthreads 1 -force -debug

mkdir -p ${DATADIR}/fixels/intemplatespace

foreach -10 ${DATADIR}/warps/*wm_in_template_space.mif : srun -c 1 fod2fixel IN -mask ${DATADIR}/voxel_mask.mif ${DATADIR}/fixels/intemplatespace/UNIP -afd fd.mif -force -nthreads 1 -debug

foreach -10 ${DATADIR}/fixels/intemplatespace/* : srun -c 1 fixelreorient IN ${DATADIR}/warps/NAME2template_warp.mif ${DATADIR}/fixels/intemplatespace/NAME -force -nthreads 1 -debug

#NOTE: Leave fixelcorrespondence and warp2metric as "foreach -1" - see: http://community.mrtrix.org/t/fixel-analysis-pipeline-index-mif-files-are-smaller-than-expected/1010/6

foreach -1 ${DATADIR}/fixels/intemplatespace/* : srun -c 10 fixelcorrespondence IN/fd.mif ${DATADIR}/fixel_mask ${DATADIR}/fixels/fd NAME.mif -force -nthreads 10 -debug

foreach -1 ${WORKDIR}/${NORMDIR}/upsample/FODS/wm/*.mif : srun -c 10 warp2metric ${DATADIR}/warps/UNIP2template_warp.mif -fc ${DATADIR}/fixel_mask ${DATADIR}/fixels/fc UNIP.mif -force -nthreads 10 -debug


mkdir -p ${DATADIR}/fixels/log_fc

cp ${DATADIR}/fixels/fc/index.mif ${DATADIR}/fixels/fc/directions.mif ${DATADIR}/fixels/log_fc

foreach -10 ${WORKDIR}/${NORMDIR}/upsample/FODS/wm/*.mif : srun -c 1 mrcalc ${DATADIR}/fixels/fc/UNIP.mif -log ${DATADIR}/fixels/log_fc/UNIP.mif -nthreads 1 -force


mkdir -p ${DATADIR}/fixels/fdc

cp ${DATADIR}/fixels/fc/index.mif ${DATADIR}/fixels/fc/directions.mif ${DATADIR}/fixels/fdc

foreach -10 ${WORKDIR}/${NORMDIR}/upsample/FODS/wm/*.mif : srun -c 1 mrcalc ${DATADIR}/fixels/fd/UNIP.mif ${DATADIR}/fixels/fc/UNIP.mif -mult ${DATADIR}/fixels/fdc/UNIP.mif -nthreads 1 -force
