#!/bin/bash
#file: intensitynormandrespfx
#usage: intensitynormandrespfx $WORKDIR $subjs $OUTDIR

WORKDIR=$1
OUTDIR=$2

mkdir -p ${WORKDIR}/${OUTDIR}
mkdir -p ${WORKDIR}/${OUTDIR}/DWI
mkdir -p ${WORKDIR}/${OUTDIR}/Masks
mkdir -p ${WORKDIR}/${OUTDIR}/DWInorm

nargs=$#

if [ "$nargs" == 2 ]; then
	DATADIR=${WORKDIR}/Diff
else
	DATADIR=${WORKDIR}/$3
fi

cd ${WORKDIR}/${OUTDIR}

find ${DATADIR}/* -maxdepth 0 -type d | awk -F "/" '{print $NF}' > ${WORKDIR}/${OUTDIR}/scans.txt

for subj in `cat ${WORKDIR}/${OUTDIR}/scans.txt`; do
rsync ${DATADIR}/${subj}/preproc/biascorr.mif ${WORKDIR}/${OUTDIR}/DWI/${subj}_DWI.mif
rsync ${DATADIR}/${subj}/preproc/biasmeanb0bet_mask.nii.gz ${WORKDIR}/${OUTDIR}/Masks/${subj}_Mask.nii.gz
done


#srun -c 10 dwiintensitynorm ${WORKDIR}/${OUTDIR}/DWI ${WORKDIR}/${OUTDIR}/Masks ${WORKDIR}/${OUTDIR}/DWInorm ${WORKDIR}/${OUTDIR}/fa_template.mif ${WORKDIR}/${OUTDIR}/fa_template_wm_mask.mif -tempdir . -nocleanup -force -nthreads 10

foreach -10 ${WORKDIR}/${OUTDIR}/DWInorm/*DWI.mif : srun -c 1 dwi2tensor IN ${WORKDIR}/${OUTDIR}/DWInorm/UNIP_dt.mif -mask ${WORKDIR}/${OUTDIR}/Masks/UNIP_Mask.nii.gz -nthreads 0 -force

foreach -10 ${WORKDIR}/${OUTDIR}/DWInorm/*dt.mif : srun -c 1 tensor2metric IN -fa ${WORKDIR}/${OUTDIR}/DWInorm/UNIP_fa.nii -mask ${WORKDIR}/${OUTDIR}/Masks/UNIP_Mask.nii.gz -nthreads 0 -force

foreach -10 ${WORKDIR}/${OUTDIR}/DWInorm/*dt.mif : srun -c 1 tensor2metric IN -adc ${WORKDIR}/${OUTDIR}/DWInorm/UNIP_md.nii -mask ${WORKDIR}/${OUTDIR}/Masks/UNIP_Mask.nii.gz -nthreads 0 -force


mkdir -p ${WORKDIR}/${OUTDIR}/FODS

foreach -10 ${WORKDIR}/${OUTDIR}/DWInorm/*DWI.mif : srun -c 1 dwi2response dhollander IN ${WORKDIR}/${OUTDIR}/FODS/UNIP_wm.txt ${WORKDIR}/${OUTDIR}/FODS/UNIP_gm.txt ${WORKDIR}/${OUTDIR}/FODS/UNIP_csf.txt -mask ${WORKDIR}/${OUTDIR}/Masks/UNIP_Mask.nii.gz -nthreads 0 -force 

rm ${WORKDIR}/${OUTDIR}/FODS/avg_wm_resp.txt

rm ${WORKDIR}/${OUTDIR}/FODS/avg_csf_resp.txt

srun -c 1 average_response ${WORKDIR}/${OUTDIR}/FODS/*wm.txt ${WORKDIR}/${OUTDIR}/FODS/avg_wm_resp.txt

srun -c 1 average_response ${WORKDIR}/${OUTDIR}/FODS/*csf.txt ${WORKDIR}/${OUTDIR}/FODS/avg_csf_resp.txt

foreach -10 ${WORKDIR}/${OUTDIR}/DWInorm/*DWI.mif : srun -c 1 dwi2fod msmt_csd IN ${WORKDIR}/${OUTDIR}/FODS/avg_wm_resp.txt ${WORKDIR}/${OUTDIR}/FODS/UNIP_wm.mif ${WORKDIR}/${OUTDIR}/FODS/avg_csf_resp.txt ${WORKDIR}/${OUTDIR}/FODS/UNIP_csf.mif -nthreads 0 -force -mask ${WORKDIR}/${OUTDIR}/Masks/UNIP_Mask.nii.gz
