#!/bin/bash
#file: intensitynormandrespfx
#usage: intensitynormandrespfx $WORKDIR $subjs $OUTDIR

WORKDIR=$1
subjs="$2"
OUTDIR=$3

mkdir -p ${WORKDIR}/${OUTDIR}
mkdir -p ${WORKDIR}/${OUTDIR}/DWI
mkdir -p ${WORKDIR}/${OUTDIR}/Masks
mkidr -p ${WORKDIR}/${OUTDIR}/DWInorm

nargs=$#

if [ "$nargs" == 3]; then
	DATADIR=${WORKDIR}/Diff
else
	DATADIR=${WORKDIR}/$4
fi

cd ${OUTDIR}

#find ${DATADIR}/* -maxdepth 0 -type d | awk -F "/" '{print $NF}' > scans.txt

for subj in `cat ${subjs}`; do
rsync ${DATADIR}/${subj}/preproc/biascorr.mif DWI/${subj}_DWI.mif
rsync ${DATADIR}/${subj}/preproc/biasmeanb0bet_mask.nii.gz Masks/${subj}_Mask.nii.gz
done

dwiintensitynorm ${WORKDIR}/${OUTDIR}/DWI ${WORKDIR}/${OUTDIR}/Masks ${WORKDIR}/${OUTDIR}/DWInorm ${WORKDIR}/${OUTDIR}/fa_template.mif ${WORKDIR}/${OUTDIR}/fa_template_wm_mask.mif -tempdir . -nocleanup -force -nthreads $ncpus

mkdir -p ${WORKDIR}/${OUTDIR}/FODS

foreach -N 10 DWInorm/*.mif : dwi2response dhollander IN ${WORKDIR}/${OUTDIR}/FODS/UNIwm.txt ${WORKDIR}/${OUTDIR}/FODS/UNIgm.txt ${WORKDIR}/${OUTDIR}/FODS/UNIcsf.txt -mask ${WORKDIR}/${OUTDIR}/UNI_Mask.nii.gz -nthreads 0 -force

average_response */wm.txt ${WORKDIR}/${OUTDIR}/group_average_response.txt

average_response */csf.txt ${WORKDIR}/${OUTDIR}/group_average_response.txt

foreach -N 10 * : dwi2fod msmt_csd biascorr.mif wm.txt wm.mif csf.txt csf.mif -force -mask biasmeanb0bet_mask.nii.gz 


