#!/bin/bash
#usage: upsampleandfods subj WORKDIR NORMDIR VOXSIZE OUTDIR

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2
NORMDIR=$3
VOXSIZE=$4
OUTDIR=$5

cd ${WORKDIR}/${NORMDIR}

mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}
mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI
mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks
mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS

foreach -10 ${WORKDIR}/${NORMDIR}/DWInorm/*DWI.mif : mrresize IN -vox $VOXSIZE ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI/UNIP_DWI.mif -nthreads 1 -force 

foreach -10 ${WORKDIR}/${NORMDIR}/DWInorm/*.nii.gz : mrresize IN -vox $VOXSIZE ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks/UNIP_Mask.mif -interp nearest -nthreads 1 -force 

foreach -10 ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI/*DWI.mif : dwi2fod msmt_csd IN ${WORKDIR}/${NORMDIR}/FODS/avg_wm_resp.txt ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/UNIP_wm.mif ${WORKDIR}/${NORMDIR}/FODS/avg_csf_resp.txt ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/UNIP_csf.mif -nthreads 1 -force -mask ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks/UNIP_Mask.mif
