#!/bin/bash
#usage: upsampleandfods subj WORKDIR NORMDIR VOXSIZE OUTDIR

#compulsory arguments that are called automatically:
#subj=$1
WORKDIR=$1
NORMDIR=$2
VOXSIZE=$3

cd ${WORKDIR}/${NORMDIR}

OUTDIR=upsample

mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}
mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI
mkdir ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks
mkdir -p ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm
mkdir -p ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/csf


foreach -10 ${WORKDIR}/${NORMDIR}/DWInorm/*DWI.mif : srun -c 1 mrresize IN -vox $VOXSIZE ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI/UNIP_DWI.mif -nthreads 0 -force 

foreach -10 ${WORKDIR}/${NORMDIR}/Masks/*.nii* : srun -c 1 mrresize IN -vox $VOXSIZE ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks/UNIP_Mask.mif -interp nearest -nthreads 0 -force 

foreach -10 ${WORKDIR}/${NORMDIR}/${OUTDIR}/DWI/*DWI.mif : srun -c 1 dwi2fod msmt_csd IN ${WORKDIR}/${NORMDIR}/FODS/avg_wm_resp.txt ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm/UNIP_wm.mif ${WORKDIR}/${NORMDIR}/FODS/avg_csf_resp.txt ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/csf/UNIP_csf.mif -nthreads 0 -force -mask ${WORKDIR}/${NORMDIR}/${OUTDIR}/Masks/UNIP_Mask.mif

foreach -10 ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm/*wm.mif : srun -c 1 mrconvert IN ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm/UNIP_wm_str.mif -strides +1,2,3,4 -force -nthreads 0 

foreach -10 ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm/*wm_str.mif : mv IN ${WORKDIR}/${NORMDIR}/${OUTDIR}/FODS/wm/UNIP_wm.mif
