#!/bin/bash 
#file: advfulldiffsteps

subj=$1
WORKDIR=$2
#FS_DIR=$3

#arguments to be set
ismultiband=1
parc=DST
ismultishell=1
numfibers=25M


#Full diffusion pipeline, from pre-processing to connectome construction - using the advanced version

#Advanced preprocessing
#Parameters: multiband (1 if yes)

advpreproc_pre_eddy $subj $WORKDIR $ismultiband


