#!/bin/bash

#usage: advpreproc

subj=$1
WORKDIR=$2

cd $WORKDIR/Diff/$subj/preproc


mrconvert eddycorr.nii.gz eddycorr.mif -fslgrad eddycorr.eddy_rotated_bvecs bvals -nthreads $ncpus -force

dwiextract eddycorr.mif -nthreads $ncpus -bzero - | mrmath -axis 3 - mean eddymeanb0.nii -force -nthreads $ncpus

bet2 eddymeanb0.nii eddyb0brainfsl -m -f 0.15

#dwi2mask eddycorr.mif eddymaskMR.nii -force -nthreads $ncpus


#bias correction

dwibiascorrect -mask eddyb0brainfsl_mask.nii.gz -ants eddycorr.mif biascorr.mif -nthreads $ncpus -force


#create optimal mask

dwi2mask biascorr.mif biasmaskMR.nii -force -nthreads $ncpus

fslmaths eddyb0brainfsl_mask -mas biasmaskMR.nii iterbrainmask

gunzip iterbrainmask.nii.gz -f

#dwishellmath biascorr.mif mean meanshell.mif -nthreads $ncpus -force


#Create tensor and FA images

dwiextract biascorr.mif -nthreads $ncpus -bzero - | mrmath -axis 3 - mean biasmeanb0.nii -force -nthreads $ncpus

fslmaths biasmeanb0.nii -mas iterbrainmask.nii biasmeanb0masked

#gunzip -f biasmeanb0bet.nii.gz

#add further bet2 option so later pipeline doesn't break!

bet2 biasmeanb0masked biasmeanb0bet -f 0.10 -m 

dwi2tensor biascorr.mif dt.nii -mask iterbrainmask.nii -nthreads $ncpus -force

tensor2metric dt.nii -fa fa.nii -nthreads $ncpus -force
