#!/bin/bash

#usage: eddy_gpu subj workdir ncpus

subj=$1
WORKDIR=$2
ismultiband=$3

nargs=$#

if [ "$nargs" == 3 ]; then
	DATADIR=${WORKDIR}/Diff
else
	DATADIR=${WORKDIR}/$4
fi

cd $DATADIR/$subj/preproc

#Preprocessing steps including eddy correction & bias correction (WIP)

fslmerge -t b0APPA b0AP.nii b0PA.nii

nvols=`mrinfo rawdataAPdn.mif -nthreads 0 -quiet | grep Dimensions| awk '{print $8}'`

rsync -vazu $pipedir/data/MICRORES_slspec.txt ./slspec.txt


if ([ $ismultiband = 1 ]); then

	topup --imain=b0APPA.nii.gz --datain=acqparams.txt --config=b02b0.cnf --out=topup_results --iout=topup_b0
	fslmaths topup_b0 -Tmean topup_b01
	bet topup_b01.nii.gz binary -m -f 0.2
	eddy_cuda9.1 --imain=rawdataAPdn.nii --mask=binary_mask.nii.gz --acqp=acqparams.txt --index=index.txt --bvecs=bvecs --bvals=bvals --topup=topup_results --data_is_shelled --slm=linear --repol --ol_nstd=7 --mporder=$(($nvols/3)) --s2v_niter=10 --s2v_lambda=5 --slspec=slspec.txt --out=eddycorr

else

	topup --imain=b0APPA.nii.gz --datain=acqparams.txt --config=b02b0.cnf --out=topup_results --iout=topup_b0
	fslmaths topup_b0 -Tmean topup_b01
	bet topup_b01.nii.gz binary -m -f 0.2
	eddy_cuda9.1 --imain=rawdataAPdn.nii --mask=binary_mask.nii.gz --acqp=acqparams.txt --index=index.txt --bvecs=bvecs --bvals=bvals --topup=topup_results --slm=linear --repol --ol_std=7 --mporder=$(($nvols/3)) --s2v_niter=10 --s2v_lambda=5 --slspec=slspec.txt --out=eddycorr

fi
