#!/bin/bash
#file: fibertrackandcntmecon
#usage: fibertrackandcntmecon ismultishell numfibers  cntmeprefix

subj=$1
WORKDIR=$2
numfibers=$3
CNTMEPREFIX=$4

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi


#Multi-tissue spherical deconvolution

dwi2response dhollander biascorr.mif wm.txt gm.txt csf.txt -mask biasmeanb0bet_mask.nii.gz -nthreads $ncpus -force

dwi2fod msmt_csd biascorr.mif wm.txt wm.mif gm.txt gm.mif csf.txt csf.mif -force -mask biasmeanb0bet_mask.nii.gz -nthreads $ncpus



mrconvert wm.mif wmstr.mif -stride +1,2,3,4 -nthreads $ncpus -force

mv wmstr.mif wm.mif

fod2dec wm.mif  foddec.mif -mask biasmeanb0bet_mask.nii.gz -force -nthreads $ncpus


#Fiber tracking

tckgen wm.mif $(numfibers).tck -seed_dynamic wm.mif -minlength 10 -maxlength 250 -number $numfibers -mask wmseg025.nii -output_seeds succeeds.txt -force -nthreads $ncpus

tckmap $(numfibers).tck $(numfibers).mif -vox 0.5 -force -nthreads $ncpus

tckgen wm.mif 1M.tck -seed_dynamic wm.mif -minlength 10 -maxlength 250 -number 1M -mask wmseg025.nii  -output_seeds succeeds1M.txt -force -nthreads $ncpus

tckmap 1M.tck 1M.mif -vox 0.5 -force -nthreads $ncpus


#tcksift2

tcksift2 $(numfibers).tck wm.mif sift_weightfactor.txt -mask wmseg025.nii -force -nthreads $ncpus

tcksift2 1M.tck wm.mif 1Msift_weightfactor.txt -mask wmseg05.nii -force -nthreads $ncpus


#Connectome construction
#sifted

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_streamweights.csv -tck_weights_in sift_weightfactor.txt -assignment_radial_search 2 -zero_diagonal -out_assignments streamlineassignment.txt -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_invlengthweights.csv -tck_weights_in sift_weightfactor.txt -assignment_radial_search 2 -zero_diagonal -scale_invlength -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_invnodelengthweights.csv -tck_weights_in sift_weightfactor.txt -assignment_radial_search 2 -zero_diagonal -scale_invlength -scale_invnodevol -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_meanfiberlengths.csv -tck_weights_in sift_weightfactor.txt -assignment_radial_search 2 -zero_diagonal -scale_length -stat_edge mean -force


#non-sifted
tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_streamweights_nosift.csv -assignment_radial_search 2 -zero_diagonal -out_assignments streamlineassignment.txt -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_invlengthweights_nosift.csv -assignment_radial_search 2 -zero_diagonal -scale_invlength -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_invnodelengthweights_nosift.csv  -assignment_radial_search 2 -zero_diagonal -scale_invlength -scale_invnodevol -force

tck2connectome $(numfibers).tck rparc_fixsubcort.nii $(CNTMEPREFIX)_meanfiberlengths_nosift.csv  -assignment_radial_search 2 -zero_diagonal -scale_length -stat_edge mean -force


#Alter sift tracks for visualisation purposes

tckedit 1M.tck -tck_weights_in 1Msift_weightfactor.txt  1Msift.tck -force -nthreads $ncpus

tckmap 1Msift.tck 1Msift.mif -vox 0.5 -force -nthreads $ncpus
