#!/bin/bash
# file: advpreproc
# usage: advpreproc subj workdir ismosaic ncpus fullreverseseq ismultiband

# note: for only with acquisitions with reverse sequnce - i.e. base subject directory must contain rawdataAP.mif and its reverse sequence rawdataPA.mif

subj=$1
WORKDIR=$2
#ismosiac=$3
#fullreverseseq=$4
#ismultiband=$5

mkdir -p $WORKDIR/Diff/$subj/preproc

rsync *rawdata* $WORKDIR/Diff/$subj/preproc

rsync T1.nii $WORKDIR/Diff/$subj/preproc

cd $WORKDIR/Diff/$subj/preproc


#check for extra b0 volume

srun -c 1 mrinfo rawdataAP.mif -dwgrad > rawencoding.b

#nvols=$(wc -l rawencoding.b | awk -F " " '{print $1}')

#embed phase encoding

srun -c 1 mrconvert rawdataAP.mif rawdataAPsetPE.mif -set_property PhaseEncoding j- -nthreads 1 -force

srun -c 1 mrconvert rawdataPA.mif rawdataPAsetPE.mif -set_property PhaseEncoding j -nthreads 1 -force

mv rawdataPAsetPE.mif rawdataPA.mif
mv rawdataAPsetPE.mif rawdataAP.mif


#embed reverse encoding direction

srun -c 1 mrconvert rawdataPA.mif rawdataPAaddenc.mif -grad ${WORKDIR}/revencoding.b -nthreads 1 -force 

mv rawdataPAaddenc.mif rawdataPA.mif

#Denoise

srun -c 8 dwidenoise rawdataAP.mif rawdataAPdn.mif -force -nthreads 8
srun -c 8 dwidenoise rawdataPA.mif rawdataPAdn.mif -force -nthreads 8

srun -c 1 mrconvert rawdataAPdn.mif rawdataAPdnstr.mif -strides +1,2,3,4 -force -nthreads 1
srun -c 1 mrconvert rawdataAPdnstr.mif  rawdataAPdn.mif  -force -nthreads 1

srun -c 1 mrconvert rawdataPAdn.mif rawdataPAdnstr.mif -strides +1,2,3,4 -force -nthreads 1
srun -c 1 mrconvert rawdataPAdnstr.mif rawdataPAdn.mif -strides +1,2,3,4 -force -nthreads 1

rm rawdataAPdnstr.mif
rm rawdataPAdnstr.mif 

#Generate a b0 base image for each phase-encoding direction

srun -c 1 mrconvert rawdataAPdn.mif b0AP.mif -coord 3 0 -force -nthreads 1
srun -c 1 mrconvert rawdataPAdn.mif b0PA.mif -coord 3 0 -force -nthreads 1

#Preprocessing steps including eddy correction & bias correction

srun -c 8 dwiextract rawdataAPdn.mif APb0s.mif -nthreads 8 -bzero -force
srun -c 8 dwiextract rawdataPAdn.mif PAb0s.mif -nthreads 8 -bzero -force

#srun -c 8 mrconvert APb0s.mif AP8b0s.mif -coord 3 0,1,3,5,7,9,10 -force -nthreads 8

#dwiextract rawdataPAdn.mif rawdatPAdnrem.mif -bzero -force -nthreads 8 
#mv rawdataPAdnrem.mif rawdataPAdn.mif
#mrconvert rawdataPAdn.mif rawdataPAdnrem.mif -coord 3 0,1,2,3,4,5,6 -force -nthreads 8

#mv rawdataPAdnrem.mif rawdataPAdn.mif

srun -c 1 mrcat APb0s.mif PAb0s.mif allb0s.mif -axis 3 -force -nthreads 1

#dwipreproc_cust -rpe_pair AP7b0s.mif  rawdataPAdn.mif -export_grad_mrtrix adjencoding.b AP rawdataAPdn.mif eddycorr.mif -nthreads 8 -verbose -force

srun -c 8 dwipreproc -rpe_pair -se_epi allb0s.mif -align_seepi -pe_dir AP -export_grad_mrtrix adjencoding.b rawdataAPdn.mif eddycorr.mif -eddy_options " --repol " -nthreads 8 -force -eddyqc_all dwipreproc

#extract motion parameters
#preprocdir=$(find * -maxdepth 0 -name "*dwipreproc*" -type d)
#awk -F " " '{print $2}' ${preprocdir}/dwi_post_eddy.eddy_movement_rms > FD.txt
#awk '{ total += $1 } END { print total/NR }' FD.txt > meanFD.txt

srun -c 1 dwiextract eddycorr.mif -nthreads 1 -bzero - | mrmath -axis 3 - mean eddymeanb0.nii -nthreads 1 -force

srun -c 1 bet2 eddymeanb0.nii eddyb0brainfsl -m -f 0.15



#bet2 eddymeanb0.nii eddymeanb0bet -m -f 0.15

srun -c 8 dwibiascorrect -mask eddyb0brainfsl_mask.nii.gz -fsl eddycorr.mif biascorr.mif -nthreads 8 -force


#create optimal mask

#dwi2mask biascorr.mif biasmaskMR.nii -force -nthreads 8

#fslmaths eddyb0brainfsl_mask.nii.gz -mas biasmaskMR.nii iterbrainmask

#gunzip iterbrainmask.nii.gz -f

#dwishellmath biascorr.mif mean meanshell.mif -force -nthreads 8


#Create tensor and FA images

srun -c 8 dwiextract biascorr.mif -nthreads 8 -bzero - | mrmath -axis 3 - mean biasmeanb0.nii -nthreads 8 -force

srun -c 1 bet2 biasmeanb0.nii biasmeanb0bet -f 0.2 -m

#fslmaths biasmeanb0.nii -mask iterbrainmask.nii biasmeanb0bet

#gunzip biasmeanb0bet.nii.gz -f 

srun -c 8 dwi2tensor biascorr.mif dt.nii -mask biasmeanb0bet_mask.nii.gz -nthreads 8 -force

srun -c 8 tensor2metric dt.nii -fa fa.nii -nthreads 8 -force
