#!/bin/bash
#usage: seedbasedtracking subj WORKDIR NORMDIR

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2
NORMDIR=$3
PARCDIR=$4
parcimageref=$5
seedtracklist=$6

#convert to convert appropriate directory structure
PARCDIR=${WORKDIR}/${PARCDIR}
seedtracklist=${WORKDIR}/${seedtracklist}

#option to include extra  argument ($6), if diffusion data directory has changed
#e.g: if files are now located in "Diff-wcust5tt"
#usage: seedbasedtracking $subj $WORKDIR $NORMDIR Diff-wcust5tt

nargs=$#

if [ "$nargs" == 6 ]; then
	DATADIR=${WORKDIR}/Diff
else
	DATADIR=${WORKDIR}/$7
fi

echo "Normalized diffusion data are contained in ${WORKDIR}/${NORMDIR}"
cd ${WORKDIR}/${NORMDIR}

mkdir -p ${WORKDIR}/${NORMDIR}/seedtracking/${subj}
cd ${WORKDIR}/${NORMDIR}/seedtracking/${subj}

#Setup transforms between FS, MNI, and Diff space

#standard flirt - registrationn for now (will change to ANTS)

flirt -ref ${PARCDIR}/${parcimageref}.nii -in ${DATADIR}/${subj}/preproc/brainFS.nii -omat FS2MNI.mat -out FS2MNI -dof 12

fnirt --in=${DATADIR}/${subj}/preproc/brainFS.nii --aff=FS2MNI.mat --cout=FS_nonlinear_transf_2MNI --config=T1_2_MNI152_2mm

#redundant - but good for QC purposes
applywarp --ref=${PARCDIR}/${parcimageref}.nii --in=${DATADIR}/${subj}/preproc/brainFS.nii --warp=FS_nonlinear_transf_2MNI --out=FS_nonlinear_warped_2MNI

#setup inverse for ROI masks

invwarp --ref=${DATADIR}/${subj}/preproc/brainFS.nii --warp=FS_nonlinear_transf_2MNI --out=FS_nonlinear_transf_2MNI_INV

while read line

do 

seed=$(echo $line | cut -d " " -f 1) 
target=$(echo $line | cut -d " " -f 2)

echo "tracking for $seed to $target" #may do reverse later

#Setup seeds in diffusion space

applywarp --ref=${DATADIR}/${subj}/preproc/brainFS.nii --in=${PARCDIR}/${seed}.nii --warp=FS_nonlinear_transf_2MNI_INV --out=${seed}_FS --interp=nn

gunzip ${seed}_FS.nii.gz -f

mrconvert ${seed}_FS.nii ${seed}_FS_str.nii -strides -1,3,-2 -force -nthreads 5

flirt -in ${seed}_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out ${seed}_diff.nii.gz -applyxfm -init  ${DATADIR}/${subj}/preproc/FS2diff.mat -interp nearestneighbour

gunzip ${seed}_diff.nii.gz -f


#now left-hem
 
#flirt -in /mnt/lustre/home/$USER/base/rLSTN_MNI.nii -ref ${DATADIR}/${subj}/preproc/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out LSTN_FS.nii.gz

#gunzip LSTN_FS.nii.gz -f

#mrconvert LSTN_FS.nii LSTN_FS_str.nii -strides -1,3,-2 -force -nthreads 5

#flirt -in LSTN_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out LSTN_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip LSTN_diff.nii.gz -f


#Setup include masks in diffusion space, plus tracking 

applywarp --ref=${DATADIR}/${subj}/preproc/brainFS.nii --in=${PARCDIR}/${target}.nii --warp=FS_nonlinear_transf_2MNI_INV --out=${target}_FS --interp=nn

gunzip ${target}_FS.nii.gz -f
 
mrconvert ${target}_FS.nii ${target}_FS_str.nii -strides -1,3,-2 -force -nthreads 5
 
flirt -in ${target}_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out ${target}_diff.nii.gz -applyxfm -init ${DATADIR}/${subj}/preproc/FS2diff.mat -interp nearestneighbour

gunzip ${target}_diff.nii.gz -f
 
tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -seed_image ${seed}_diff.nii -include ${target}_diff.nii -mask ${DATADIR}/${subj}/preproc/wmseg025.nii -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads 5 -output_seeds ${seed}_seeds.txt


#repeat for left-hemisphere

#flirt -in /mnt/lustre/home/$USER/base/HCP_LSMA.nii -ref ${DATADIR}/${subj}/preproc/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_LSMA_FS.nii.gz

#gunzip HCP_LSMA_FS.nii.gz
 
#mrconvert HCP_LSMA_FS.nii HCP_LSMA_FS_str.nii -strides -1,3,-2 -force -nthreads 5
 
#flirt -in HCP_LSMA_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out HCP_LSMA_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip HCP_LSMA_diff.nii.gz
 
#tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif LSTNtoHCPLSMA.tck -seed_image LSTN_diff.nii -include HCP_LSMA_diff.nii -act ${DATADIR}/${subj}/preproc/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads 5 -output_seeds LSTNseeds.txt


#NOWIFG
#Ant
#flirt -in /mnt/lustre/home/$USER/base/HCP_RIFG_Ant.nii -ref ${DATADIR}/${subj}/preproc/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_RIFG_Ant_FS.nii.gz

#gunzip HCP_RIFG_Ant_FS.nii.gz -f
 
#mrconvert HCP_RIFG_Ant_FS.nii HCP_RIFG_Ant_FS_str.nii -strides -1,3,-2 -force -nthreads 5
 
#flirt -in HCP_RIFG_Ant_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out HCP_RIFG_Ant_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip HCP_RIFG_Ant_diff.nii.gz -f
 
#tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}toHCPRIFG_Ant.tck -seed_image ${seed}_diff.nii -include HCP_RIFG_Ant_diff.nii -act ${DATADIR}/${subj}/preproc/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads 5 -output_seeds ${seed}seedstoRIFG_Ant.txt

#Post
#flirt -in /mnt/lustre/home/$USER/base/HCP_RIFG_Post.nii -ref ${DATADIR}/${subj}/preproc/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_RIFG_Post_FS.nii.gz

#gunzip HCP_RIFG_Post_FS.nii.gz -f
 
#mrconvert HCP_RIFG_Post_FS.nii HCP_RIFG_Post_FS_str.nii -strides -1,3,-2 -force -nthreads 5
 
#flirt -in HCP_RIFG_Post_FS_str.nii -ref ${DATADIR}/${subj}/preproc/fa.nii -out HCP_RIFG_Post_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip HCP_RIFG_Post_diff.nii.gz -f
 
#tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}toHCPRIFG_Post.tck -seed_image ${seed}_diff.nii -include HCP_RIFG_Post_diff.nii -act ${DATADIR}/${subj}/preproc/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads 5 -output_seeds ${seed}seedstoRIFG_Post.txt
#calculate normalized tensor images - note will turn off once data has been constructed again (from intensitynormalization)

#dwi2tensor ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_DWI.mif ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_dt.mif -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii.gz -nthreads 5 -force

#tensor2metric ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_dt.mif -fa ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii.gz -nthreads 5 -force

#tensor2metric ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_dt.mif -adc ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii.gz -nthreads 5 -force



#calculate metrics
#TDI

tckmap ${seed}_to_${target}.tck ${seed}_to_${target}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads 5 -force #this is actually useful in looking at the track density

mrthreshold ${seed}_to_${target}_tdi.nii ${seed}_to_${target}_tdi_thr.nii -nthreads 5 -force -abs 1 #parameter can be changed to exclude noisey fibers


#tckmap LSTNtoHCPLSMA.tck LSTNtoHCPLSMA_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads 5 -force #this is actually useful in looking at the track density

#mrthreshold LSTNtoHCPLSMA_tdi.nii LSTNtoHCPLSMA_tdi_thr.nii -nthreads 5 -force -abs 1 #parameter can be changed to exclude noisey fibers


#tckmap ${seed}toHCPRIFG_Ant.tck ${seed}toHCPRIFG_Ant_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads 5 -force #this is actually useful in looking at the track density

#mrthreshold ${seed}toHCPRIFG_Ant_tdi.nii ${seed}toHCPRIFG_Ant_tdi_thr.nii -nthreads 5 -force -abs 1 #parameter can be changed to exclude noisey fibers


#tckmap ${seed}toHCPRIFG_Post.tck ${seed}toHCPRIFG_Post_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads 5 -force #this is actually useful in looking at the track density

#mrthreshold ${seed}toHCPRIFG_Post_tdi.nii ${seed}toHCPRIFG_Post_tdi_thr.nii -nthreads 5 -force -abs 1 #parameter can be changed to exclude noisey fibers


#FA

mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}_to_${target}_meanFA.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask LSTNtoHCPLSMA_tdi_thr.nii -nthreads 5 -force -output mean > LSTNtoHCPLSMA_meanFA.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}toHCPRIFG_Ant_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}toHCPRIFG_Ant_meanFA.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}toHCPRIFG_Post_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}toHCPRIFG_Post_meanFA.txt

#MD

mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}_to_${target}_meanMD.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask LSTNtoHCPLSMA_tdi_thr.nii -nthreads 5 -force -output mean > LSTNtoHCPLSMA_meanMD.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}toHCPRIFG_Ant_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}toHCPRIFG_Ant_meanMD.txt

#mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}toHCPRIFG_Post_tdi_thr.nii -nthreads 5 -force -output mean > ${seed}toHCPRIFG_Post_meanMD.txt

#AFD

afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -nthreads 5 -all_fixels -force -afd_map ${seed}_to_${target}_AFD.nii > ${seed}_to_${target}_AFD.txt

#afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif LSTNtoHCPLSMA.tck -nthreads 5 -all_fixels -force -afd_map LSTNtoHCPLSMA_AFD.nii > LSTNtoHCPLSMA_AFD.txt

#afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}toHCPRIFG_Ant.tck -nthreads 5 -all_fixels -force -afd_map ${seed}toHCPRIFG_Ant_AFD.nii > ${seed}toHCPRIFG_Ant_AFD.txt

#afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}toHCPRIFG_Post.tck -nthreads 5 -all_fixels -force -afd_map ${seed}toHCPRIFG_Post_AFD.nii > ${seed}toHCPRIFG_Post_AFD.txt

done < $seedtracklist

#Extract successful seeds as images
#cut -d ',' -f 3-5 LSTNseeds.txt > LSTNcolseeds.txt

#cut -d ',' -f 3-5 ${seed}seeds.txt > ${seed}colseeds.txt

#sed 1d LSTNcolseeds.txt > LSTNcolseedsnohead.txt

#mv LSTNcolseedsnohead.txt LSTNseeds.txt

#sed 1d ${seed}colseeds.txt > ${seed}colseedsnohead.txt

#mv ${seed}colseedsnohead.txt ${seed}seeds.txt

#rm ${seed}colseeds.txt

#rm LSTNcolseeds.txt

#tckconvert ${seed}seeds.txt ${seed}seeds.tck -nthreads 5 -force

#tckmap ${seed}seeds.tck ${seed}seeds.nii -upsample 1 -force -nthreads 5 -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii

#tckconvert LSTNseeds.txt LSTNseeds.tck -nthreads 5 -force

#tckmap LSTNseeds.tck LSTNseeds.nii -upsample 1 -force -nthreads 5 -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii
