#!/bin/bash
#usage: seedbasedtracking $subj $WORKDIR

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2

#option to include extra command argument ($3), if diffusion data directory has changed
#e.g: if files are now located in "Diff-wcust5tt"
#usage: seedbasedtracking $subj $WORKDIR Diff-wcust5tt

nargs=$#

rundir=$(pwd)

if [ "$nargs" == 2]; then
	if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
	cd $WORKDIR/Diff/$subj/preproc
	fi
else
	cd ${WORKDIR}/${3}/${subj}/preproc
fi

currrundir=$(pwd)
mkdir seedtracking
cd seedtracking


#Setup transforms between FS, MNI, and Diff space

flirt -ref /mnt/lustre/home/$USER/base/mni_hires_t1_brain.nii -in ${currrundir}/brainFS.nii -omat FS2MNIhires.mat -out FS2MNIhiris -dof 12

convert_xfm -omat MNIhires2FS.mat -inverse FS2MNIhires.mat

convert_xfm -omat FS2diff.mat -inverse ${currrundir}/diff2FS.mat


#Setup STN seeds in diffusion space

flirt -in /mnt/lustre/home/$USER/base/rRSTN_MNI.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out RSTN_FS.nii.gz

gunzip RSTN_FS.nii.gz

mrconvert RSTN_FS.nii RSTN_FS_str.nii -stride -1,3,-2 -force -nthreads 8

flirt -in RSTN_FS_str.nii -ref ${currrundir}/fa.nii -out RSTN_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip RSTN_diff.nii.gz


#now left-hem
 
flirt -in /mnt/lustre/home/$USER/base/rLSTN_MNI.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out LSTN_FS.nii.gz

gunzip LSTN_FS.nii.gz

mrconvert LSTN_FS.nii LSTN_FS_str.nii -stride -1,3,-2 -force -nthreads 8

flirt -in LSTN_FS_str.nii -ref ${currrundir}/fa.nii -out LSTN_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip LSTN_diff.nii.gz



#Setup include masks in diffusion space, plus tracking 


flirt -in /mnt/lustre/home/$USER/base/HCP_RSMA.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_RSMA_FS.nii.gz

gunzip HCP_RSMA_FS.nii.gz
 
mrconvert HCP_RSMA_FS.nii HCP_RSMA_FS_str.nii -stride -1,3,-2 -force -nthreads 8
 
flirt -in HCP_RSMA_FS_str.nii -ref ${currrundir}/fa.nii -out HCP_RSMA_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip HCP_RSMA_diff.nii.gz
 
tckgen ${currrundir}/wm.mif RSTNtoHCPRSMA.tck -seed_image RSTN_diff.nii -include HCP_RSMA_diff.nii -act ${currrundir}/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads 8


#repeat for left-hemisphere


flirt -in /mnt/lustre/home/$USER/base/HCP_LSMA.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_LSMA_FS.nii.gz

gunzip HCP_LSMA_FS.nii.gz
 
mrconvert HCP_LSMA_FS.nii HCP_LSMA_FS_str.nii -stride -1,3,-2 -force -nthreads 8
 
flirt -in HCP_LSMA_FS_str.nii -ref ${currrundir}/fa.nii -out HCP_LSMA_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip HCP_LSMA_diff.nii.gz
 
tckgen ${currrundir}/wm.mif LSTNtoHCPLSMA.tck -seed_image LSTN_diff.nii -include HCP_LSMA_diff.nii -act ${currrundir}/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads 8


#calculate metrics

tckmap RSTNtoHCPRSMA.tck RSTNtoHCPRSMA_tdi.nii -template ${currrundir}/fa.nii #this is actually useful in looking at the track density

mrthreshold RSTNtoHCPRSMA_tdi.nii RSTNtoHCPRSMA_tdi_thr.nii -abs 1 #parameter can be changed to exclude noisey fibers

mrstats ${currrundir}/fa.nii -mask RSTNtoHCPRSMA_tdi_thr.nii -output mean > RSTNtoHCPRSMA_meanFA.txt


tckmap LSTNtoHCPLSMA.tck LSTNtoHCPLSMA_tdi.nii -template ${currrundir}/fa.nii #this is actually useful in looking at the track density

mrthreshold LSTNtoHCPLSMA_tdi.nii LSTNtoHCPLSMA_tdi_thr.nii -abs 1 #parameter can be changed to exclude noisey fibers

mrstats ${currrundir}/fa.nii -mask LSTNtoHCPLSMA_tdi_thr.nii -output mean > LSTNtoHCPLSMA_meanFA.txt
