#!/bin/bash
#usage: seedbasedtracking $subj $WORKDIR $PARCDIR $parcimageref

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2
PARCDIR=$3
parcimageref=$4

#option to include extra command argument ($3), if diffusion data directory has changed
#e.g: if files are now located in "Diff-wcust5tt"
#usage: seedbasedtracking $subj $WORKDIR Diff-wcust5tt

#convert to appropriate directory structure

PARCDIR=${WORKDIR}/${PARCDIR}

rundir=$(pwd)

cd $WORKDIR/Diff/$subj/preproc

currrundir=$(pwd)
mkdir seedtracking
cd seedtracking


#Setup transforms between FS, MNI, and Diff space

rsync ${currrundir}/brainFS.nii .

bet2 brainFS.nii brainFSbet -f 0.2 -m

gunzip brainFSbet.nii.gz

#add nthreads for ANTs

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$ncpus
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS

parcimageref=${parcimageref}.nii

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [brainFSintemp,brainFSintempWarped.nii.gz,brainFSintempInverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [${PARCDIR}/${parcimageref},brainFSbet.nii,1] --transform Rigid[0.1] --metric MI[${PARCDIR}/${parcimageref},brainFSbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[${PARCDIR}/${parcimageref},brainFSbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[${PARCDIR}/${parcimageref},brainFSbet.nii,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

#flirt -ref ${PARCDIR}/mni_hires_t1_brain.nii -in ${DATADIR}/${subj}/preproc/brainFS.nii -omat FS2MNIhires.mat -out FS2MNIhiris -dof 12

#convert_xfm -omat tempinbrainFS.mat -inverse FS2MNIhires.mat

c3d_affine_tool -ref brainFSintempWarped.nii.gz -src brainFSbet.nii -itk brainFSintemp0GenericAffine.mat -ras2fsl -o brainFSintemp-fsl.mat

#now inverse it

rsync ${currrundir}/FS2diff.mat .
rsync ${currrundir}/diff2FS.mat .

convert_xfm -omat tempinbrainFS.mat -inverse brainFSintemp-fsl.mat

convert_xfm -omat FS2diff.mat -inverse diff2FS.mat


#Setup STN seeds in diffusion space

flirt -in ${PARCDIR}/RPFC.nii.gz -ref brainFS.nii -applyxfm -init tempinbrainFS.mat -interp nearestneighbour -out RPFC_FS.nii.gz

gunzip RPFC_FS.nii.gz -f

mrconvert RPFC_FS.nii RPFC_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus

flirt -in RPFC_FS_str.nii -ref ${currrundir}/biasmeanb0bet.nii.gz -out RPFC_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip RPFC_diff.nii.gz -f


#now left-hem
 
#flirt -in /mnt/lustre/home/$USER/base/rLSTN_MNI.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out LSTN_FS.nii.gz

#gunzip LSTN_FS.nii.gz

#mrconvert LSTN_FS.nii LSTN_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus

#flirt -in LSTN_FS_str.nii -ref ${currrundir}/fa.nii -out LSTN_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip LSTN_diff.nii.gz



#Setup include masks in diffusion space, plus tracking 

flirt -in ${currrundir}/rinsula.nii.gz -ref brainFS.nii -applyxfm -init tempinbrainFS.mat -interp nearestneighbour -out rinsula_FS.nii.gz

gunzip rinsula_FS.nii.gz -f
 
mrconvert rinsula_FS.nii rinsula_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus
 
flirt -in rinsula_FS_str.nii -ref ${currrundir}/biasmeanb0bet.nii.gz -out rinsula_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

gunzip rinsula_diff.nii.gz -f
 
tckgen ${currrundir}/wm.mif RPFC2Insula.tck -seed_image RPFC_diff.nii -include rinsula_diff.nii -mask ${currrundir}/iterbrainmask.nii -select 100 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds RPFC_seeds.txt

#repeat for left-hemisphere


#flirt -in /mnt/lustre/home/$USER/base/HCP_LSMA.nii -ref ${currrundir}/brainFS.nii -applyxfm -init MNIhires2FS.mat -interp nearestneighbour -out HCP_LSMA_FS.nii.gz

#gunzip HCP_LSMA_FS.nii.gz
 
#mrconvert HCP_LSMA_FS.nii HCP_LSMA_FS_str.nii -stride -1,3,-2 -force -nthreads $ncpus
 
#flirt -in HCP_LSMA_FS_str.nii -ref ${currrundir}/fa.nii -out HCP_LSMA_diff.nii.gz -applyxfm -init FS2diff.mat -interp nearestneighbour

#gunzip HCP_LSMA_diff.nii.gz
 
#tckgen ${currrundir}/wm.mif LSTNtoHCPLSMA.tck -seed_image LSTN_diff.nii -include HCP_LSMA_diff.nii -act ${currrundir}/r5TT.nii -number 100 -maxlength 250 -maxnum 0 -stop -unidirectional -force -nthreads $ncpus


#calculate metrics

tckmap RPFC2RInsula.tck RPFC2RInsula_tdi.nii -template ${currrundir}/fa.nii #this is actually useful in looking at the track density

mrthreshold RPFC2RInsula_tdi.nii RPFC2RInsula_tdi_thr.nii -abs 1 #parameter can be changed to exclude noisey fibers

mrstats ${currrundir}/fa.nii -mask RPFC2RInsula_tdi_thr.nii -output mean > RPFC2RInsula_meanFA.txt


#tckmap LSTNtoHCPLSMA.tck LSTNtoHCPLSMA_tdi.nii -template ${currrundir}/fa.nii #this is actually useful in looking at the track density

#mrthreshold LSTNtoHCPLSMA_tdi.nii LSTNtoHCPLSMA_tdi_thr.nii -abs 1 #parameter can be changed to exclude noisey fibers

#mrstats ${currrundir}/fa.nii -mask LSTNtoHCPLSMA_tdi_thr.nii -output mean > LSTNtoHCPLSMA_meanFA.txt
