#!/bin/bash
#usage: seedbasedtracking subj WORKDIR NORMDIR

#compulsory arguments that are called automatically:
subj=$1
WORKDIR=$2
NORMDIR=$3
PARCDIR=$4
parcimageref=$5
seedtracklist=$6

#convert to convert appropriate directory structure
PARCDIR=${WORKDIR}/${PARCDIR}
seedtracklist=${WORKDIR}/${seedtracklist}

#option to include extra  argument ($4), if diffusion data directory has changed
#e.g: if files are now located in "Diff-wcust5tt"
#usage: seedbasedtracking $subj $WORKDIR $NORMDIR Diff-wcust5tt

nargs=$#

if [ "$nargs" == 6 ]; then
	DATADIR=${WORKDIR}/Diff
else
	DATADIR=${WORKDIR}/$7
fi

echo "Normalized diffusion data are contained in ${WORKDIR}/${NORMDIR}"
cd ${WORKDIR}/${NORMDIR}

mkdir -p ${WORKDIR}/${NORMDIR}/seedtracking-ANTs/${subj}
cd ${WORKDIR}/${NORMDIR}/seedtracking-ANTs/${subj}


#Setup transforms between FS, MNI, and Diff space

#standard flirt - registrationn for now (will change to ANTS)

rsync ${DATADIR}/${subj}/preproc/brainFSsp.nii .

bet2 brainFSsp.nii brainFSspbet -f 0.2 -m 

gunzip brainFSspbet.nii.gz


#add nthreads for ANTs

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$ncpus
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS


#now run

parcimageref=${parcimageref}.nii

mrconvert ${PARCDIR}/${parcimageref} ${parcimageref}_FSstr.nii -strides -1,3,-2 -force -nthreads 1


if [ ! -f brainFSintemp0GenericAffine.mat ]; then

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [brainFSintemp,brainFSintempWarped.nii.gz,brainFSintempInverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [${parcimageref}_FSstr.nii,brainFSspbet.nii,1] --transform Rigid[0.1] --metric MI[${parcimageref}_FSstr.nii,brainFSspbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[${parcimageref}_FSstr.nii,brainFSspbet.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[${parcimageref}_FSstr.nii,brainFSspbet.nii,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

fi


#Create inverse of bbregister (for diff to freesurfer sp)

convert_xfm -omat FS2diff.mat -inverse ${DATADIR}/${subj}/preproc/diff2FS.mat


#Convert it into ANTs format

c3d_affine_tool -ref ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -src brainFSsp.nii FS2diff.mat -fsl2ras -oitk FS2diff-ANTs.mat


#Apply transforms

while read line

do 

seed=$(echo $line | cut -d " " -f 1) 
target=$(echo $line | cut -d " " -f 2)

echo "tracking for $seed to $target" 


#Setup STN seeds in diffusion space

mrconvert ${PARCDIR}/${target}.nii ${target}_FSstr.nii -strides 1,-3,-2 -force -nthreads 1

mrconvert ${PARCDIR}/${seed}.nii ${seed}_FSstr.nii -strides 1,-3,-2 -force -nthreads 1
 

antsApplyTransforms -d 3 -r ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -i ${seed}_FSstr.nii -t [brainFSintemp0GenericAffine.mat,1] -t FS2diff-ANTs.mat -o ${seed}_diff.nii -n NearestNeighbor

antsApplyTransforms -d 3 -r ${DATADIR}/${subj}/preproc/biasmeanb0bet.nii.gz -i ${target}_FSstr.nii -t [brainFSintemp0GenericAffine.mat,1] -t FS2diff-ANTs.mat -o ${target}_diff.nii -n NearestNeighbor
 

#Finally the tracking

tckgen ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -seed_image ${seed}_diff.nii -include ${target}_diff.nii -mask ${WORKDIR}/${NORMDIR}/Masks/${subj}_Mask.nii -seeds 50000 -maxlength 250 -stop -seed_unidirectional -force -nthreads $ncpus -output_seeds ${seed}_seeds.txt


#calculate metrics

#TDI

tckmap ${seed}_to_${target}.tck ${seed}_to_${target}_tdi.nii -template ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -nthreads $ncpus -force #this is actually useful in looking at the track density

mrthreshold ${seed}_to_${target}_tdi.nii ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -abs 1 #parameter can be changed to exclude noisey fibers


#FA

mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_fa.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanFA.txt

#MD

mrstats ${WORKDIR}/${NORMDIR}/DWInorm/${subj}_md.nii -mask ${seed}_to_${target}_tdi_thr.nii -nthreads $ncpus -force -output mean > ${seed}_to_${target}_meanMD.txt

#AFD

afdconnectivity ${WORKDIR}/${NORMDIR}/FODS/${subj}_wm.mif ${seed}_to_${target}.tck -nthreads $ncpus -all_fixels -force -afd_map ${seed}_to_${target}_AFD.nii > ${seed}_to_${target}_AFD.txt

tckstats ${seed}_to_${target}.tck -output count -nthreads $ncpus -quiet -force > ${seed}_to_${target}_count.txt

done < $seedtracklist
