#!/bin/bash
#file : segparcandcoregT1
#usage: segparcandcoregT1 <subj> <SUBJECTS_DIR> parctype

#FSparctype options = "DES" (desikan, 68 rois) or DST (destrieux; 148)

subj=$1
WORKDIR=$2
parctype=$3

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

SUBJECTS_DIR=${WORKDIR}/FS

#prepare anatomical volumes for segmentation, parcellation correction, and then co-registration to diffusion space

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFS.nii -strides +1,2,3 -nthreads 8 -force

mrconvert $SUBJECTS_DIR/$subj/mri/T1.mgz FS.nii -strides +1,2,3 -nthreads 8 -force

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFSsp.nii -nthreads 8 -force

#add steps to go from T1 native to FS space (redundant here, but applicable to Phil's STN approaches)

bet2 T1.nii T1bet -f 0.15

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFSsp.nii -nthreads 8 -force

flirt -ref T1bet.nii.gz -in brainFSsp.nii -dof 6 -out FS2FSL -omat FS2FSL.mat

convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat



#5TT setup and cust 5TTgen script (unique to Phil)

flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat mni2FS.mat -dof 12

convert_xfm -omat FS2mni.mat -inverse mni2FS.mat

#flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat FS2mni.mat -dof 12 -applyxfm -init FS2mni.mat

5ttgen_alt brainFS.nii FS2mni.mat 5TTFSmasked.nii

#bet2 T1.nii T1bet -f 0.15

5tt2gmwmi 5TTFSmasked.nii 5TTgmwmi.nii -nthreads 8 -force


#parcellation setup

labelconvert $SUBJECTS_DIR/$subj/mri/aparc.a2009s+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/src/connectome/tables/fs_a2009s.txt parc.nii -nthreads 8 -force

#flirt -ref T1bet.nii.gz -in parc.nii -applyxfm -init FS2FSL.mat -interp nearestneighbour -out parcFSL.nii.gz

rm parc_fixsubcort.nii

mrconvert parc.nii parctempstr.nii -strides -1,2,3 -force -nthreads 8

labelsgmfix parctempstr.nii brainFS.nii $MRTRIX/src/connectome/tables/fs_a2009s.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads 8

mrconvert parc_fixsubcort.nii parc_fixsubcortstr.nii -strides +1,2,3

mv parc_fixsubcortstr.nii parc_fixsubcort.nii

rm parctempstr.nii


#Coregistrations setup


#FSL co-registration of T1 to diffusion image (& subsequent 5TT file)

#flirt -ref eddyb0.nii -in T1.nii -omat T1FSLtoDiff.mat -dof 6

#transformconvert T1FSLtoDiff.mat T1.nii eddyb0.nii flirt_import T1FSLtoDiffMR.mat -force

#mrtransform 5TTFSL.nii -linear T1FSLtoDiffMR.mat r5TTFSL.nii -force

bbregister --s $subj --mov biasmeanb0bet.nii.gz --init-fsl --reg register.dat --dti --fslmat diff2FS.mat

transformconvert diff2FS.mat biasmeanb0bet.nii.gz $SUBJECTS_DIR/$subj/mri/brain.mgz flirt_import diff2FSMR.mat -force

mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFS.nii -linear diff2FSMR.mat -inverse -force

mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFSrg.nii -linear diff2FSMR.mat -inverse -template fa.nii -force



mrconvert 5TTgmwmi.nii 5TTFSspgmwmi.nii -strides -1,3,-2 -nthreads 8 -force

mrtransform 5TTFSspgmwmi.nii r5TTgmwmi.nii -linear diff2FSMR.mat -inverse -force

mrconvert 5TTFSmasked.nii 5TTFSspmasked.nii -strides -1,3,-2 -nthreads 8 -force

mrtransform 5TTFSspmasked.nii r5TT.nii -linear diff2FSMR.mat -inverse -force

mrconvert parc_fixsubcort.nii parc_FSspfixsubcort.nii -strides -1,3,-2 -nthreads 8 -force

#convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

#flirt -ref brainFSsp.nii -in parc_fixsubcort.nii -applyxfm -init FSL2FS.mat -interp nearestneighbour -out parc_fixsubcortFS.nii.gz

convert_xfm -omat FS2diff.mat  -inverse diff2FS.mat

flirt -ref fa.nii -in parc_FSspfixsubcort.nii -applyxfm -init FS2diff.mat -out rparc_fixsubcort.nii.gz  -interp nearestneighbour

#mrtransform parc_fixsubcort.nii rparc_fixsubcort.nii -linear diff2FSMR.mat -inverse -interp nearest -template biasmeanb0bet.nii.gz -force


#FS co-registration of T1 to diffusion image (& subsequent 5TT file)


#mrconvert 5TTFSmasked.nii wmseg.nii -coord 3 2

#flirt -ref brain.nii -in fa.nii -out DiffinFS -omat DiffinFS.mat -dof 6 -cost bbr  -wmseg wmseg.nii

#transformconvert DiffinFS.mat b0bet.nii.gz brain.nii flirt_import DiffinFSMR.mat -force

#mrtransform T1FS.nii -linear DiffinFSMR.mat rT1FSbbr.nii -force -inverse

#mrtransform 5TTFSmasked.nii -linear FSinDiffMR.mat r5TTFSmasked.nii -force 


gunzip -f rparc_fixsubcort.nii.gz

#setup 5TT file for modified fiber tracking - unique to phil

mrconvert r5TT.nii r5TT.mif -nthreads 8 -force

mrconvert r5TT.mif wmseg.nii -coord 3 2 -nthreads 8 -force

mrthreshold wmseg.nii -abs 0.5 wmseg05.nii -force -nthreads 8

mrthreshold wmseg.nii -abs 0.25 wmseg025.nii -force -nthreads 8

mrthreshold wmseg.nii -abs 0.75 wmseg075.nii -force -nthreads 8
