#!/bin/bash

subj=$1
WORKDIR=$2
tracksbasename=$3
parc=$4
CNTMEPREFIX=$5

currdir=$(pwd)
#scannum=$(basename $currdir)

#if [ "$currdir" != "$WORKDIR/Diff/$subj/preproc/${scannum}" ]; then
#cd $WORKDIR/Diff/$subj/preproc/${scannum}
#fi

if [ "$currdir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

echo "Realigning template into subject space"

#Co-register low-resolution FA into high-resolution template

#flirt -ref fa.nii -in $FSLDIR/data/standard/FMRIB58_FA_1mm.nii.gz -out MNItofa -omat MNItofa.mat -cost mutualinfo -- removed  140117 - registration inaccurate
flirt -ref fa.nii -in $FSLDIR/data/standard/FMRIB58_FA_1mm.nii.gz -out MNItofa -omat MNItofa.mat -cost normmi

#Parcellation template into subject space

flirt -ref fa.nii -in $parc -out ${CNTMEPREFIX}_flirted_uniform -applyxfm -init MNItofa.mat -interp nearestneighbour

gunzip -f ${CNTMEPREFIX}_flirted_uniform.nii.gz


#check if connectomes have been zippeed

gunzip ${tracksbasename}.tck.gz

#Connectome construction
#Track lengths

tck2connectome ${tracksbasename}.tck ${CNTMEPREFIX}_flirted_uniform.nii connectome_${CNTMEPREFIX}_tracklengths.csv -scale_length -zero_diagonal -assignment_radial_search 2 -force -nthreads $ncpus -stat_edge mean

#Streamline/Length
tck2connectome ${tracksbasename}.tck ${CNTMEPREFIX}_flirted_uniform.nii connectome_${CNTMEPREFIX}_invlengths.csv -scale_invlength -zero_diagonal -assignment_radial_search 2 -force -nthreads $ncpus

#Streamline count
tck2connectome ${tracksbasename}.tck ${CNTMEPREFIX}_flirted_uniform.nii connectome_${CNTMEPREFIX}_trackcount.csv -zero_diagonal -assignment_radial_search 2 -force -nthreads $ncpus

tck2connectome ${tracksbasename}.tck ${CNTMEPREFIX}_flirted_uniform.nii connectome_${CNTMEPREFIX}_invnodeandlengths.csv -scale_invnodevol -scale_invlength -zero_diagonal -assignment_radial_search 2 -force -nthreads $ncpus

#rezip

gzip ${tracksbasename}.tck
