#!/bin/bash

# All required resource statements start with "#PBS -l"
# These will be interpreted by the job submission system (PBS pro)

subj=$1
WORKDIR=$2

mkdir -p $WORKDIR/Diff/$subj/preproc

rsync *rawdata* $WORKDIR/Diff/$subj/preproc

rsync *encoding* $WORKDIR/Diff/$subj/preproc

cd $WORKDIR/Diff/$subj/preproc


#Import gradient table for MRtrix specs

mrconvert rawdata.nii.gz rawdata.mif -grad rawencoding.b -stride +1,2,3,4 -force -nthreads $ncpus

#cp rawdata.mif preproc 

#Denoise the rawdata

dwidenoise rawdata.mif rawdata-dn.mif -force -nthreads $ncpus

#Re-convert to the correct stride

mrconvert rawdata-dn.mif rawdata-dnstr.mif -stride +1,2,3,4 -force -nthreads $ncpus
 
mrconvert rawdata-dnstr.mif  rawdata-dn.mif -stride +1,2,3,4 -force -nthreads $ncpus

rm rawdata-dnstr.mif

#Eddy and motion correction

dwipreproc -rpe_none -pe_dir AP -export_grad_mrtrix adjencoding.b rawdata-dn.mif eddycorr.mif -eddy_options " --repol " -nthreads $ncpus -debug -tempdir . -nocleanup -force

#Construct the b0 mask for future processing 

mrconvert eddycorr.mif eddyb0.nii -coord 3 0 -force -nthreads $ncpus

bet2 eddyb0.nii eddyb0brainfsl -m -f 0.15


#Bias correction

dwibiascorrect -mask iterbrainmask.nii -fsl eddycorr.mif biascorr.mif -force -nthreads $ncpus -tempdir .


#create optimal mask

dwi2mask biascorr.mif biasmaskMR.nii -force -nthreads $ncpus

fslmaths eddyb0brainfsl_mask -mas biasmaskMR.nii iterbrainmask

gunzip iterbrainmask.nii.gz -f

fslmaths biasmeanb0.nii -mask iterbrainmask.nii biasmeanb0bet

#mrconvert biascorr.mif biasb0.nii -coord 3 0 -force -nthreads $ncpus
#bet2 biasb0.nii biasb0brain -m -f 0.15

#Generate tensor and fa images

dwishellmath biascorr.mif mean meanshell.mif -force -nthreads $ncpus

dwi2tensor biascorr.mif dt.nii -mask iterbrainmask.nii -force -nthreads $ncpus

tensor2metric dt.nii -fa fa.nii -force -nthreads $ncpus
