#!/bin/bash
#file : segparcandcoregT1
#usage: segparcandcoregT1 <subj> <WORKDIR> parctype

#FSparctype options = "DES" (desikan, 68 rois) or DST (destrieux; 148)

subj=$1
WORKDIR=$2
parctype=$3
PRESEGDIR=$4

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

SUBJECTS_DIR=${WORKDIR}/FS

if [ -n "$4" ]; then
echo "SEGMENTATION HAS ALREADY BEEN PERFORMED"

subjPRESEGDIR=${WORKDIR}/${PRESEGDIR}/${subj}

echo "Subject segmentations located in ${subjPRESEGDIR}"

fi


#prepare anatomical volume for segmentation, parcellation correction, and then co-registration to diffusion space

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFS.nii -strides +1,2,3 -nthreads $ncpus -force

mrconvert $SUBJECTS_DIR/$subj/mri/T1.mgz FS.nii -nthreads $ncpus -force

#flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat mni2FS.mat -dof 12

#convert_xfm -omat FS2mni.mat -inverse mni2FS.mat

#flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat FS2mni.mat -dof 12 -applyxfm -init FS2mni.mat

#5ttgen_alt brainFS.nii FS2mni.mat 5TTfsl.nii


bet T1.nii T1bet -B

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFSsp.nii -nthreads $ncpus -force


#flirt -ref T1bet.nii.gz -in brainFSsp.nii -dof 6 -out FS2FSL -omat FS2FSL.mat

#convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

#bet2 FS2FSL.nii.gz FS2FSLbet -f 0.15 -m

#fslmaths T1bet.nii.gz -mas FS2FSLbet_mask.nii.gz T1betFSmasked.nii.gz


tkregister2 --mov $SUBJECTS_DIR/$subj/mri/brain.mgz --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --reg register.native.dat --noedit --regheader --fslregout FS2FSL.mat 

mri_vol2vol --mov $SUBJECTS_DIR/$subj/mri/brain.mgz --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --regheader --o brainFSnat.nii

#fast -B --nopve brainFSnat.nii


#5ttgen fsl T1betFSmasked.nii.gz -nocrop -premasked -sgm_amyg_hipp 5TTfsl.nii -nthreads $ncpus -force -tempdir . -nocleanup

if [ -n "$4" ]; then
echo "SEGMENTATION already perform | expect tissues to have filenames: GM.nii WM.nii CSF.nii"

5ttgen_manual brainFSnat.nii 5TT.nii ${subjPRESEGDIR}

else

5ttgen fsl brainFSnat.nii 5TT.nii -sgm_amyg_hipp -premasked -nocrop -nthreads $ncpus -force -nocleanup -tempdir .

fi

5tt2gmwmi 5TT.nii 5TTgmwmi.nii -nthreads $ncpus -force

if [ $parctype=="DES" ]; then
	echo "${parctype} parcellation being constructed"
	labelconvert $SUBJECTS_DIR/$subj/mri/aparc+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/share/mrtrix3/labelconvert/fs_default.txt parc.nii -nthreads $ncpus -force
if [ $parctype=="DST" ]; then
	echo "${parctype} parcellation being constructed"
	labelconvert $SUBJECTS_DIR/$subj/mri/aparc.a2009s+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc.nii -nthreads $ncpus -force
fi
if [ $parctype=="HCPMMP1" ]; then
	echo "${parctype} parcellation being constructed"
	mrconvert $SUBJECTS_DIR/glasser/$subj/HCPMMP1.nii.gz HCPMMP1str.nii -strides +1,2,3 -nthreads $ncpus -force
	labelconvert HCPMMP1str.nii.gz $MRTRIX/share/mrtrix3/labelconvert/hcpmmp1_original.txt $MRTRIX/share/mrtrix3/labelconvert/hcpmmp1_ordered.txt parc.nii -nthreads $ncpus -force
fi

mri_vol2vol --mov parc.nii --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --reg register.native.dat --o parcFSL.nii.gz --nearest --keep-precision

#flirt -ref T1bet.nii.gz -in parc.nii -applyxfm -init FS2FSL.mat -interp nearestneighbour -out parcFSL.nii.gz

rm parc_fixsubcort.nii

mrconvert parcFSL.nii.gz parcFSLtempstr.nii.gz -strides -1,2,3 -force -nthreads $ncpus

#if [ $parctype=="DES" ]; then
#      labelsgmfix parcFSLtempstr.nii.gz T1betFSmasked_restore.nii.gz $MRTRIX/share/mrtrix3/labelconvert/fs_default.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads $ncpus -force
#elif [ $parctype=="DST" ]; then
       labelsgmfix parcFSLtempstr.nii.gz brainFSnat.nii $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads $ncpus -force
#fi

mrconvert parc_fixsubcort.nii parc_fixsubcortstr.nii -strides +1,2,3 -force -nthreads $ncpus

mv parc_fixsubcortstr.nii parc_fixsubcort.nii

rm parcFSLtempstr.nii.gz


#Coregistrations setup


#FSL co-registration of T1 to diffusion image (& subsequent 5TT file)

#flirt -ref eddyb0.nii -in T1.nii -omat T1FSLtoDiff.mat -dof 6

#transformconvert T1FSLtoDiff.mat T1.nii eddyb0.nii flirt_import T1FSLtoDiffMR.mat -force

#mrtransform 5TTFSL.nii -linear T1FSLtoDiffMR.mat r5TTFSL.nii -force


bbregister --s $subj --mov biasmeanb0bet.nii.gz --init-fsl --reg register.dat --dti --fslmat diff2FS.mat

transformconvert diff2FS.mat biasmeanb0bet.nii.gz $SUBJECTS_DIR/$subj/mri/brain.mgz flirt_import diff2FSMR.mat -force -nthreads $ncpus

mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFS.nii -linear diff2FSMR.mat -inverse -force -nthreads $ncpus
 
mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFSrg.nii -linear diff2FSMR.mat -inverse -template fa.nii -force -nthreads $ncpus

mrconvert rFSrg.nii rFSrgstr.nii -strides +1,2,3 -nthreads $ncpus -force 

mv rFSrgstr.nii rFSrg.nii


#Move other files from T1 space

transformconvert FS2FSL.mat brainFSsp.nii T1bet.nii.gz flirt_import FS2FSLMR.mat -force -nthreads $ncpus

mrtransform 5TT.nii 5TTFSspmasked.nii -linear FS2FSLMR.mat -inverse -force -nthreads $ncpus

mrtransform 5TTgmwmi.nii 5TTFSspgmwmi.nii -linear FS2FSLMR.mat -inverse -force -nthreads $ncpus

mrtransform 5TTFSspgmwmi.nii r5TTgmwmi.nii -linear diff2FSMR.mat -inverse -force -nthreads $ncpus

mrtransform 5TTFSspmasked.nii r5TT.nii -linear diff2FSMR.mat -inverse -force -nthreads $ncpus

convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

flirt -ref brainFSsp.nii -in parc_fixsubcort.nii -applyxfm -init FSL2FS.mat -interp nearestneighbour -out parc_fixsubcortFS.nii.gz

convert_xfm -omat FS2diff.mat  -inverse diff2FS.mat

flirt -ref fa.nii -in parc_fixsubcortFS.nii.gz -applyxfm -init FS2diff.mat -out rparc_fixsubcort.nii.gz  -interp nearestneighbour

#mrtransform parc_fixsubcort.nii rparc_fixsubcort.nii -linear diff2FSMR.mat -inverse -interp nearest -template biasmeanb0bet.nii.gz -force


#FS co-registration of T1 to diffusion image (& subsequent 5TT file)


#mrconvert 5TTfsl.nii wmseg.nii -coord 3 2

#flirt -ref brain.nii -in fa.nii -out DiffinFS -omat DiffinFS.mat -dof 6 -cost bbr  -wmseg wmseg.nii

#transformconvert DiffinFS.mat b0bet.nii.gz brain.nii flirt_import DiffinFSMR.mat -force

#mrtransform T1FS.nii -linear DiffinFSMR.mat rT1FSbbr.nii -force -inverse

#mrtransform 5TTfsl.nii -linear FSinDiffMR.mat r5TTfsl.nii -force 


gunzip -f rparc_fixsubcort.nii.gz
