#!/bin/bash
#file : segparcandcoregT1
#usage: segparcandcoregT1 <subj> <WORKDIR> parctype

#FSparctype options = "DES" (desikan, 68 rois) or DST (destrieux; 148)

subj=$1
WORKDIR=$2
parctype=$3
PRESEGDIR=$4

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

SUBJECTS_DIR=${WORKDIR}/FS

if [ -n "$4" ]; then
echo "SEGMENTATION HAS ALREADY BEEN PERFORMED"

subjPRESEGDIR=${WORKDIR}/${PRESEGDIR}/${subj}

echo "Subject segmentations located in ${subjPRESEGDIR}"

fi


#prepare anatomical volume for segmentation, parcellation correction, and then co-registration to diffusion space

srun -c 1 mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFS.nii -strides +1,2,3 -nthreads 1 -force

srun -c 1 mrconvert $SUBJECTS_DIR/$subj/mri/T1.mgz FS.nii -nthreads 1 -force

#flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat mni2FS.mat -dof 12

#convert_xfm -omat FS2mni.mat -inverse mni2FS.mat

#flirt -in $FSLDIR/data/standard/MNI152_T1_1mm_brain.nii.gz -ref brainFS.nii -omat FS2mni.mat -dof 12 -applyxfm -init FS2mni.mat

#5ttgen_alt brainFS.nii FS2mni.mat 5TTfsl.nii


srun -c 1 bet2 T1.nii T1bet -f 0.15

srun -c 1 mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFSsp.nii -nthreads 1 -force


#flirt -ref T1bet.nii.gz -in brainFSsp.nii -dof 6 -out FS2FSL -omat FS2FSL.mat

#convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

#bet2 FS2FSL.nii.gz FS2FSLbet -f 0.15 -m

#fslmaths T1bet.nii.gz -mas FS2FSLbet_mask.nii.gz T1betFSmasked.nii.gz


srun -c 1 tkregister2 --mov $SUBJECTS_DIR/$subj/mri/brain.mgz --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --reg register.native.dat --noedit --regheader --fslregout FS2FSL.mat 

srun -c 1 mri_vol2vol --mov $SUBJECTS_DIR/$subj/mri/brain.mgz --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --regheader --o brainFSnat.nii

export FSLSUB_IGNORE_SLURM=1

srun -c 1 fast -B --nopve brainFSnat.nii


#5ttgen fsl T1betFSmasked.nii.gz -nocrop -premasked -sgm_amyg_hipp 5TTfsl.nii -nthreads $ncpus -force -tempdir . -nocleanup

if [ -n "$4" ]; then
echo "SEGMENTATION already perform | expect tissues to have filenames: GM.nii WM.nii CSF.nii"

srun -c 1 5ttgen_manual brainFSnat_restore.nii.gz 5TT.nii ${subjPRESEGDIR}

else

srun -c 8 5ttgen fsl brainFSnat_restore.nii.gz 5TT.nii -sgm_amyg_hipp -premasked -nocrop -nthreads 8 -force -nocleanup -tempdir .

fi

srun -c 1 5tt2gmwmi 5TT.nii 5TTgmwmi.nii -nthreads 1 -force

#if [ $parctype=="DES" ]; then
#	echo "${parctype} parcellation being constructed"
#	labelconvert $SUBJECTS_DIR/$subj/mri/aparc+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/share/mrtrix3/labelconvert/fs_default.txt parc.nii -nthreads $ncpus -force
#elif [ $parctype=="DST" ]; then
	echo "${parctype} parcellation being constructed"
	srun -c 8 labelconvert $SUBJECTS_DIR/$subj/mri/aparc.a2009s+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc.nii -nthreads 8 -force #fi

srun -c 1 mri_vol2vol --mov parc.nii --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --reg register.native.dat --o parcFSL.nii.gz --nearest --keep-precision

#flirt -ref T1bet.nii.gz -in parc.nii -applyxfm -init FS2FSL.mat -interp nearestneighbour -out parcFSL.nii.gz

rm parc_fixsubcort.nii

srun -c 1 mrconvert parcFSL.nii.gz parcFSLtempstr.nii.gz -strides -1,2,3 -force -nthreads 1

#if [ $parctype=="DES" ]; then
#      labelsgmfix parcFSLtempstr.nii.gz T1betFSmasked_restore.nii.gz $MRTRIX/share/mrtrix3/labelconvert/fs_default.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads $ncpus -force
#elif [ $parctype=="DST" ]; then
     srun -c 8 labelsgmfix parcFSLtempstr.nii.gz brainFSnat_restore.nii.gz $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads 8 -force
#fi

srun -c 1 mrconvert parc_fixsubcort.nii parc_fixsubcortstr.nii -strides +1,2,3 -force -nthreads 1

mv parc_fixsubcortstr.nii parc_fixsubcort.nii

rm parcFSLtempstr.nii.gz


#Coregistrations setup


#FSL co-registration of T1 to diffusion image (& subsequent 5TT file)

#flirt -ref eddyb0.nii -in T1.nii -omat T1FSLtoDiff.mat -dof 6

#transformconvert T1FSLtoDiff.mat T1.nii eddyb0.nii flirt_import T1FSLtoDiffMR.mat -force

#mrtransform 5TTFSL.nii -linear T1FSLtoDiffMR.mat r5TTFSL.nii -force


srun -c 1 bbregister --s $subj --mov biasmeanb0bet.nii.gz --init-fsl --reg register.dat --dti --fslmat diff2FS.mat

srun -c 1 transformconvert diff2FS.mat biasmeanb0bet.nii.gz $SUBJECTS_DIR/$subj/mri/brain.mgz flirt_import diff2FSMR.mat -force -nthreads 1

srun -c 1 mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFS.nii -linear diff2FSMR.mat -inverse -force -nthreads 1
 
srun -c 1 mrtransform $SUBJECTS_DIR/$subj/mri/brain.mgz rFSrg.nii -linear diff2FSMR.mat -inverse -template fa.nii -force -nthreads 1

srun -c 1 mrconvert rFSrg.nii rFSrgstr.nii -strides +1,2,3 -nthreads 1 -force 

mv rFSrgstr.nii rFSrg.nii


#Move other files from T1 space

srun -c 1 transformconvert FS2FSL.mat brainFSsp.nii T1bet.nii.gz flirt_import FS2FSLMR.mat -force -nthreads 1

srun -c 1 mrtransform 5TT.nii 5TTFSspmasked.nii -linear FS2FSLMR.mat -inverse -force -nthreads 1

srun -c 1 mrtransform 5TTgmwmi.nii 5TTFSspgmwmi.nii -linear FS2FSLMR.mat -inverse -force -nthreads 1

srun -c 1 mrtransform 5TTFSspgmwmi.nii r5TTgmwmi.nii -linear diff2FSMR.mat -inverse -force -nthreads 1

srun -c 1 mrtransform 5TTFSspmasked.nii r5TT.nii -linear diff2FSMR.mat -inverse -force -nthreads 1

srun -c 1 convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

srun -c 1 flirt -ref brainFSsp.nii -in parc_fixsubcort.nii -applyxfm -init FSL2FS.mat -interp nearestneighbour -out parc_fixsubcortFS.nii.gz

srun -c 1 convert_xfm -omat FS2diff.mat  -inverse diff2FS.mat

srun -c 1 flirt -ref fa.nii -in parc_fixsubcortFS.nii.gz -applyxfm -init FS2diff.mat -out rparc_fixsubcort.nii.gz  -interp nearestneighbour

#mrtransform parc_fixsubcort.nii rparc_fixsubcort.nii -linear diff2FSMR.mat -inverse -interp nearest -template biasmeanb0bet.nii.gz -force


# extract WM mask for tracking

srun -c 1 mrconvert r5TT.nii r5TT.mif -force
srun -c 1 mrconvert r5TT.mif wmseg.nii -coord 3 2 -force
srun -c 1 mrthreshold wmseg.nii -abs 0.5 wmseg05.nii -force 
srun -c 1 mrthreshold wmseg.nii -abs 0.25 wmseg025.nii -force 
srun -c 1 mrthreshold wmseg.nii -abs 0.75 wmseg075.nii -force 


#mrconvert 5TTfsl.nii wmseg.nii -coord 3 2

#flirt -ref brain.nii -in fa.nii -out DiffinFS -omat DiffinFS.mat -dof 6 -cost bbr  -wmseg wmseg.nii

#transformconvert DiffinFS.mat b0bet.nii.gz brain.nii flirt_import DiffinFSMR.mat -force

#mrtransform T1FS.nii -linear DiffinFSMR.mat rT1FSbbr.nii -force -inverse

#mrtransform 5TTfsl.nii -linear FSinDiffMR.mat r5TTfsl.nii -force 


gunzip -f rparc_fixsubcort.nii.gz
